// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: webfont.proto

package io.grpc.sdk.webfont;

public interface CheckAccessKeyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:webfontsdk.CheckAccessKeyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 user_uid = 1;</code>
   */
  long getUserUid();

  /**
   * <code>uint32 font_id = 2;</code>
   */
  int getFontId();
}
