// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: webfont.proto

package io.grpc.sdk.webfont;

public interface FontBuildAccessKeyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:webfontsdk.FontBuildAccessKeyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string apikey = 1;</code>
   */
  java.lang.String getApikey();
  /**
   * <code>string apikey = 1;</code>
   */
  com.google.protobuf.ByteString
      getApikeyBytes();

  /**
   * <code>string accesskey = 2;</code>
   */
  java.lang.String getAccesskey();
  /**
   * <code>string accesskey = 2;</code>
   */
  com.google.protobuf.ByteString
      getAccesskeyBytes();

  /**
   * <code>string text = 3;</code>
   */
  java.lang.String getText();
  /**
   * <code>string text = 3;</code>
   */
  com.google.protobuf.ByteString
      getTextBytes();

  /**
   * <code>bool need_ttf = 4;</code>
   */
  boolean getNeedTtf();

  /**
   * <code>bool need_eot = 5;</code>
   */
  boolean getNeedEot();

  /**
   * <code>bool need_woff = 6;</code>
   */
  boolean getNeedWoff();

  /**
   * <code>bool need_woff2 = 7;</code>
   */
  boolean getNeedWoff2();
}
