// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: webfont.proto

package io.grpc.sdk.webfont;

/**
 * <pre>
 *字体厂商
 * </pre>
 *
 * Protobuf type {@code webfontsdk.FontMaker}
 */
public  final class FontMaker extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:webfontsdk.FontMaker)
    FontMakerOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FontMaker.newBuilder() to construct.
  private FontMaker(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FontMaker() {
    url_ = "";
    nameEn_ = "";
    nameCn_ = "";
    nameTw_ = "";
    nameJp_ = "";
    nameKr_ = "";
    introEn_ = "";
    introCn_ = "";
    introTw_ = "";
    introJp_ = "";
    introKr_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new FontMaker();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FontMaker(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            makerId_ = input.readUInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            url_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            nameEn_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            nameCn_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            nameTw_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            nameJp_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            nameKr_ = s;
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            introEn_ = s;
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();

            introCn_ = s;
            break;
          }
          case 82: {
            java.lang.String s = input.readStringRequireUtf8();

            introTw_ = s;
            break;
          }
          case 90: {
            java.lang.String s = input.readStringRequireUtf8();

            introJp_ = s;
            break;
          }
          case 98: {
            java.lang.String s = input.readStringRequireUtf8();

            introKr_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.grpc.sdk.webfont.WebfontProto.internal_static_webfontsdk_FontMaker_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.grpc.sdk.webfont.WebfontProto.internal_static_webfontsdk_FontMaker_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.grpc.sdk.webfont.FontMaker.class, io.grpc.sdk.webfont.FontMaker.Builder.class);
  }

  public static final int MAKER_ID_FIELD_NUMBER = 1;
  private int makerId_;
  /**
   * <pre>
   *厂商编号
   * </pre>
   *
   * <code>uint32 maker_id = 1;</code>
   */
  public int getMakerId() {
    return makerId_;
  }

  public static final int URL_FIELD_NUMBER = 2;
  private volatile java.lang.Object url_;
  /**
   * <pre>
   *厂商网址
   * </pre>
   *
   * <code>string url = 2;</code>
   */
  public java.lang.String getUrl() {
    java.lang.Object ref = url_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      url_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *厂商网址
   * </pre>
   *
   * <code>string url = 2;</code>
   */
  public com.google.protobuf.ByteString
      getUrlBytes() {
    java.lang.Object ref = url_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      url_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_EN_FIELD_NUMBER = 3;
  private volatile java.lang.Object nameEn_;
  /**
   * <pre>
   *字体英文名
   * </pre>
   *
   * <code>string name_en = 3;</code>
   */
  public java.lang.String getNameEn() {
    java.lang.Object ref = nameEn_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      nameEn_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *字体英文名
   * </pre>
   *
   * <code>string name_en = 3;</code>
   */
  public com.google.protobuf.ByteString
      getNameEnBytes() {
    java.lang.Object ref = nameEn_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      nameEn_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_CN_FIELD_NUMBER = 4;
  private volatile java.lang.Object nameCn_;
  /**
   * <pre>
   *字体中文名
   * </pre>
   *
   * <code>string name_cn = 4;</code>
   */
  public java.lang.String getNameCn() {
    java.lang.Object ref = nameCn_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      nameCn_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *字体中文名
   * </pre>
   *
   * <code>string name_cn = 4;</code>
   */
  public com.google.protobuf.ByteString
      getNameCnBytes() {
    java.lang.Object ref = nameCn_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      nameCn_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_TW_FIELD_NUMBER = 5;
  private volatile java.lang.Object nameTw_;
  /**
   * <pre>
   *字体繁体名
   * </pre>
   *
   * <code>string name_tw = 5;</code>
   */
  public java.lang.String getNameTw() {
    java.lang.Object ref = nameTw_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      nameTw_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *字体繁体名
   * </pre>
   *
   * <code>string name_tw = 5;</code>
   */
  public com.google.protobuf.ByteString
      getNameTwBytes() {
    java.lang.Object ref = nameTw_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      nameTw_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_JP_FIELD_NUMBER = 6;
  private volatile java.lang.Object nameJp_;
  /**
   * <pre>
   *字体日文名
   * </pre>
   *
   * <code>string name_jp = 6;</code>
   */
  public java.lang.String getNameJp() {
    java.lang.Object ref = nameJp_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      nameJp_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *字体日文名
   * </pre>
   *
   * <code>string name_jp = 6;</code>
   */
  public com.google.protobuf.ByteString
      getNameJpBytes() {
    java.lang.Object ref = nameJp_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      nameJp_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_KR_FIELD_NUMBER = 7;
  private volatile java.lang.Object nameKr_;
  /**
   * <pre>
   *字体韩语名
   * </pre>
   *
   * <code>string name_kr = 7;</code>
   */
  public java.lang.String getNameKr() {
    java.lang.Object ref = nameKr_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      nameKr_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *字体韩语名
   * </pre>
   *
   * <code>string name_kr = 7;</code>
   */
  public com.google.protobuf.ByteString
      getNameKrBytes() {
    java.lang.Object ref = nameKr_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      nameKr_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INTRO_EN_FIELD_NUMBER = 8;
  private volatile java.lang.Object introEn_;
  /**
   * <pre>
   *英语厂商介绍
   * </pre>
   *
   * <code>string intro_en = 8;</code>
   */
  public java.lang.String getIntroEn() {
    java.lang.Object ref = introEn_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      introEn_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *英语厂商介绍
   * </pre>
   *
   * <code>string intro_en = 8;</code>
   */
  public com.google.protobuf.ByteString
      getIntroEnBytes() {
    java.lang.Object ref = introEn_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      introEn_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INTRO_CN_FIELD_NUMBER = 9;
  private volatile java.lang.Object introCn_;
  /**
   * <pre>
   *中文介绍
   * </pre>
   *
   * <code>string intro_cn = 9;</code>
   */
  public java.lang.String getIntroCn() {
    java.lang.Object ref = introCn_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      introCn_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *中文介绍
   * </pre>
   *
   * <code>string intro_cn = 9;</code>
   */
  public com.google.protobuf.ByteString
      getIntroCnBytes() {
    java.lang.Object ref = introCn_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      introCn_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INTRO_TW_FIELD_NUMBER = 10;
  private volatile java.lang.Object introTw_;
  /**
   * <pre>
   *繁体中文介绍
   * </pre>
   *
   * <code>string intro_tw = 10;</code>
   */
  public java.lang.String getIntroTw() {
    java.lang.Object ref = introTw_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      introTw_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *繁体中文介绍
   * </pre>
   *
   * <code>string intro_tw = 10;</code>
   */
  public com.google.protobuf.ByteString
      getIntroTwBytes() {
    java.lang.Object ref = introTw_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      introTw_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INTRO_JP_FIELD_NUMBER = 11;
  private volatile java.lang.Object introJp_;
  /**
   * <pre>
   *日语介绍
   * </pre>
   *
   * <code>string intro_jp = 11;</code>
   */
  public java.lang.String getIntroJp() {
    java.lang.Object ref = introJp_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      introJp_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *日语介绍
   * </pre>
   *
   * <code>string intro_jp = 11;</code>
   */
  public com.google.protobuf.ByteString
      getIntroJpBytes() {
    java.lang.Object ref = introJp_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      introJp_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INTRO_KR_FIELD_NUMBER = 12;
  private volatile java.lang.Object introKr_;
  /**
   * <pre>
   *韩语介绍
   * </pre>
   *
   * <code>string intro_kr = 12;</code>
   */
  public java.lang.String getIntroKr() {
    java.lang.Object ref = introKr_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      introKr_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *韩语介绍
   * </pre>
   *
   * <code>string intro_kr = 12;</code>
   */
  public com.google.protobuf.ByteString
      getIntroKrBytes() {
    java.lang.Object ref = introKr_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      introKr_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (makerId_ != 0) {
      output.writeUInt32(1, makerId_);
    }
    if (!getUrlBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, url_);
    }
    if (!getNameEnBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, nameEn_);
    }
    if (!getNameCnBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, nameCn_);
    }
    if (!getNameTwBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, nameTw_);
    }
    if (!getNameJpBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, nameJp_);
    }
    if (!getNameKrBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, nameKr_);
    }
    if (!getIntroEnBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, introEn_);
    }
    if (!getIntroCnBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, introCn_);
    }
    if (!getIntroTwBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, introTw_);
    }
    if (!getIntroJpBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, introJp_);
    }
    if (!getIntroKrBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 12, introKr_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (makerId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, makerId_);
    }
    if (!getUrlBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, url_);
    }
    if (!getNameEnBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, nameEn_);
    }
    if (!getNameCnBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, nameCn_);
    }
    if (!getNameTwBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, nameTw_);
    }
    if (!getNameJpBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, nameJp_);
    }
    if (!getNameKrBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, nameKr_);
    }
    if (!getIntroEnBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, introEn_);
    }
    if (!getIntroCnBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, introCn_);
    }
    if (!getIntroTwBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, introTw_);
    }
    if (!getIntroJpBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, introJp_);
    }
    if (!getIntroKrBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, introKr_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.grpc.sdk.webfont.FontMaker)) {
      return super.equals(obj);
    }
    io.grpc.sdk.webfont.FontMaker other = (io.grpc.sdk.webfont.FontMaker) obj;

    if (getMakerId()
        != other.getMakerId()) return false;
    if (!getUrl()
        .equals(other.getUrl())) return false;
    if (!getNameEn()
        .equals(other.getNameEn())) return false;
    if (!getNameCn()
        .equals(other.getNameCn())) return false;
    if (!getNameTw()
        .equals(other.getNameTw())) return false;
    if (!getNameJp()
        .equals(other.getNameJp())) return false;
    if (!getNameKr()
        .equals(other.getNameKr())) return false;
    if (!getIntroEn()
        .equals(other.getIntroEn())) return false;
    if (!getIntroCn()
        .equals(other.getIntroCn())) return false;
    if (!getIntroTw()
        .equals(other.getIntroTw())) return false;
    if (!getIntroJp()
        .equals(other.getIntroJp())) return false;
    if (!getIntroKr()
        .equals(other.getIntroKr())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MAKER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getMakerId();
    hash = (37 * hash) + URL_FIELD_NUMBER;
    hash = (53 * hash) + getUrl().hashCode();
    hash = (37 * hash) + NAME_EN_FIELD_NUMBER;
    hash = (53 * hash) + getNameEn().hashCode();
    hash = (37 * hash) + NAME_CN_FIELD_NUMBER;
    hash = (53 * hash) + getNameCn().hashCode();
    hash = (37 * hash) + NAME_TW_FIELD_NUMBER;
    hash = (53 * hash) + getNameTw().hashCode();
    hash = (37 * hash) + NAME_JP_FIELD_NUMBER;
    hash = (53 * hash) + getNameJp().hashCode();
    hash = (37 * hash) + NAME_KR_FIELD_NUMBER;
    hash = (53 * hash) + getNameKr().hashCode();
    hash = (37 * hash) + INTRO_EN_FIELD_NUMBER;
    hash = (53 * hash) + getIntroEn().hashCode();
    hash = (37 * hash) + INTRO_CN_FIELD_NUMBER;
    hash = (53 * hash) + getIntroCn().hashCode();
    hash = (37 * hash) + INTRO_TW_FIELD_NUMBER;
    hash = (53 * hash) + getIntroTw().hashCode();
    hash = (37 * hash) + INTRO_JP_FIELD_NUMBER;
    hash = (53 * hash) + getIntroJp().hashCode();
    hash = (37 * hash) + INTRO_KR_FIELD_NUMBER;
    hash = (53 * hash) + getIntroKr().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.grpc.sdk.webfont.FontMaker parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.grpc.sdk.webfont.FontMaker parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.grpc.sdk.webfont.FontMaker parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.grpc.sdk.webfont.FontMaker parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.grpc.sdk.webfont.FontMaker parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.grpc.sdk.webfont.FontMaker parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.grpc.sdk.webfont.FontMaker parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.grpc.sdk.webfont.FontMaker parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.grpc.sdk.webfont.FontMaker parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.grpc.sdk.webfont.FontMaker parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.grpc.sdk.webfont.FontMaker parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.grpc.sdk.webfont.FontMaker parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.grpc.sdk.webfont.FontMaker prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *字体厂商
   * </pre>
   *
   * Protobuf type {@code webfontsdk.FontMaker}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:webfontsdk.FontMaker)
      io.grpc.sdk.webfont.FontMakerOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.grpc.sdk.webfont.WebfontProto.internal_static_webfontsdk_FontMaker_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.grpc.sdk.webfont.WebfontProto.internal_static_webfontsdk_FontMaker_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.grpc.sdk.webfont.FontMaker.class, io.grpc.sdk.webfont.FontMaker.Builder.class);
    }

    // Construct using io.grpc.sdk.webfont.FontMaker.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      makerId_ = 0;

      url_ = "";

      nameEn_ = "";

      nameCn_ = "";

      nameTw_ = "";

      nameJp_ = "";

      nameKr_ = "";

      introEn_ = "";

      introCn_ = "";

      introTw_ = "";

      introJp_ = "";

      introKr_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.grpc.sdk.webfont.WebfontProto.internal_static_webfontsdk_FontMaker_descriptor;
    }

    @java.lang.Override
    public io.grpc.sdk.webfont.FontMaker getDefaultInstanceForType() {
      return io.grpc.sdk.webfont.FontMaker.getDefaultInstance();
    }

    @java.lang.Override
    public io.grpc.sdk.webfont.FontMaker build() {
      io.grpc.sdk.webfont.FontMaker result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.grpc.sdk.webfont.FontMaker buildPartial() {
      io.grpc.sdk.webfont.FontMaker result = new io.grpc.sdk.webfont.FontMaker(this);
      result.makerId_ = makerId_;
      result.url_ = url_;
      result.nameEn_ = nameEn_;
      result.nameCn_ = nameCn_;
      result.nameTw_ = nameTw_;
      result.nameJp_ = nameJp_;
      result.nameKr_ = nameKr_;
      result.introEn_ = introEn_;
      result.introCn_ = introCn_;
      result.introTw_ = introTw_;
      result.introJp_ = introJp_;
      result.introKr_ = introKr_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.grpc.sdk.webfont.FontMaker) {
        return mergeFrom((io.grpc.sdk.webfont.FontMaker)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.grpc.sdk.webfont.FontMaker other) {
      if (other == io.grpc.sdk.webfont.FontMaker.getDefaultInstance()) return this;
      if (other.getMakerId() != 0) {
        setMakerId(other.getMakerId());
      }
      if (!other.getUrl().isEmpty()) {
        url_ = other.url_;
        onChanged();
      }
      if (!other.getNameEn().isEmpty()) {
        nameEn_ = other.nameEn_;
        onChanged();
      }
      if (!other.getNameCn().isEmpty()) {
        nameCn_ = other.nameCn_;
        onChanged();
      }
      if (!other.getNameTw().isEmpty()) {
        nameTw_ = other.nameTw_;
        onChanged();
      }
      if (!other.getNameJp().isEmpty()) {
        nameJp_ = other.nameJp_;
        onChanged();
      }
      if (!other.getNameKr().isEmpty()) {
        nameKr_ = other.nameKr_;
        onChanged();
      }
      if (!other.getIntroEn().isEmpty()) {
        introEn_ = other.introEn_;
        onChanged();
      }
      if (!other.getIntroCn().isEmpty()) {
        introCn_ = other.introCn_;
        onChanged();
      }
      if (!other.getIntroTw().isEmpty()) {
        introTw_ = other.introTw_;
        onChanged();
      }
      if (!other.getIntroJp().isEmpty()) {
        introJp_ = other.introJp_;
        onChanged();
      }
      if (!other.getIntroKr().isEmpty()) {
        introKr_ = other.introKr_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.grpc.sdk.webfont.FontMaker parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.grpc.sdk.webfont.FontMaker) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int makerId_ ;
    /**
     * <pre>
     *厂商编号
     * </pre>
     *
     * <code>uint32 maker_id = 1;</code>
     */
    public int getMakerId() {
      return makerId_;
    }
    /**
     * <pre>
     *厂商编号
     * </pre>
     *
     * <code>uint32 maker_id = 1;</code>
     */
    public Builder setMakerId(int value) {
      
      makerId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *厂商编号
     * </pre>
     *
     * <code>uint32 maker_id = 1;</code>
     */
    public Builder clearMakerId() {
      
      makerId_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object url_ = "";
    /**
     * <pre>
     *厂商网址
     * </pre>
     *
     * <code>string url = 2;</code>
     */
    public java.lang.String getUrl() {
      java.lang.Object ref = url_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        url_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *厂商网址
     * </pre>
     *
     * <code>string url = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUrlBytes() {
      java.lang.Object ref = url_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        url_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *厂商网址
     * </pre>
     *
     * <code>string url = 2;</code>
     */
    public Builder setUrl(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      url_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *厂商网址
     * </pre>
     *
     * <code>string url = 2;</code>
     */
    public Builder clearUrl() {
      
      url_ = getDefaultInstance().getUrl();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *厂商网址
     * </pre>
     *
     * <code>string url = 2;</code>
     */
    public Builder setUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      url_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object nameEn_ = "";
    /**
     * <pre>
     *字体英文名
     * </pre>
     *
     * <code>string name_en = 3;</code>
     */
    public java.lang.String getNameEn() {
      java.lang.Object ref = nameEn_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nameEn_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *字体英文名
     * </pre>
     *
     * <code>string name_en = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNameEnBytes() {
      java.lang.Object ref = nameEn_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nameEn_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *字体英文名
     * </pre>
     *
     * <code>string name_en = 3;</code>
     */
    public Builder setNameEn(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      nameEn_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *字体英文名
     * </pre>
     *
     * <code>string name_en = 3;</code>
     */
    public Builder clearNameEn() {
      
      nameEn_ = getDefaultInstance().getNameEn();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *字体英文名
     * </pre>
     *
     * <code>string name_en = 3;</code>
     */
    public Builder setNameEnBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      nameEn_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object nameCn_ = "";
    /**
     * <pre>
     *字体中文名
     * </pre>
     *
     * <code>string name_cn = 4;</code>
     */
    public java.lang.String getNameCn() {
      java.lang.Object ref = nameCn_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nameCn_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *字体中文名
     * </pre>
     *
     * <code>string name_cn = 4;</code>
     */
    public com.google.protobuf.ByteString
        getNameCnBytes() {
      java.lang.Object ref = nameCn_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nameCn_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *字体中文名
     * </pre>
     *
     * <code>string name_cn = 4;</code>
     */
    public Builder setNameCn(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      nameCn_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *字体中文名
     * </pre>
     *
     * <code>string name_cn = 4;</code>
     */
    public Builder clearNameCn() {
      
      nameCn_ = getDefaultInstance().getNameCn();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *字体中文名
     * </pre>
     *
     * <code>string name_cn = 4;</code>
     */
    public Builder setNameCnBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      nameCn_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object nameTw_ = "";
    /**
     * <pre>
     *字体繁体名
     * </pre>
     *
     * <code>string name_tw = 5;</code>
     */
    public java.lang.String getNameTw() {
      java.lang.Object ref = nameTw_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nameTw_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *字体繁体名
     * </pre>
     *
     * <code>string name_tw = 5;</code>
     */
    public com.google.protobuf.ByteString
        getNameTwBytes() {
      java.lang.Object ref = nameTw_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nameTw_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *字体繁体名
     * </pre>
     *
     * <code>string name_tw = 5;</code>
     */
    public Builder setNameTw(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      nameTw_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *字体繁体名
     * </pre>
     *
     * <code>string name_tw = 5;</code>
     */
    public Builder clearNameTw() {
      
      nameTw_ = getDefaultInstance().getNameTw();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *字体繁体名
     * </pre>
     *
     * <code>string name_tw = 5;</code>
     */
    public Builder setNameTwBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      nameTw_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object nameJp_ = "";
    /**
     * <pre>
     *字体日文名
     * </pre>
     *
     * <code>string name_jp = 6;</code>
     */
    public java.lang.String getNameJp() {
      java.lang.Object ref = nameJp_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nameJp_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *字体日文名
     * </pre>
     *
     * <code>string name_jp = 6;</code>
     */
    public com.google.protobuf.ByteString
        getNameJpBytes() {
      java.lang.Object ref = nameJp_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nameJp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *字体日文名
     * </pre>
     *
     * <code>string name_jp = 6;</code>
     */
    public Builder setNameJp(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      nameJp_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *字体日文名
     * </pre>
     *
     * <code>string name_jp = 6;</code>
     */
    public Builder clearNameJp() {
      
      nameJp_ = getDefaultInstance().getNameJp();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *字体日文名
     * </pre>
     *
     * <code>string name_jp = 6;</code>
     */
    public Builder setNameJpBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      nameJp_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object nameKr_ = "";
    /**
     * <pre>
     *字体韩语名
     * </pre>
     *
     * <code>string name_kr = 7;</code>
     */
    public java.lang.String getNameKr() {
      java.lang.Object ref = nameKr_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nameKr_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *字体韩语名
     * </pre>
     *
     * <code>string name_kr = 7;</code>
     */
    public com.google.protobuf.ByteString
        getNameKrBytes() {
      java.lang.Object ref = nameKr_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nameKr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *字体韩语名
     * </pre>
     *
     * <code>string name_kr = 7;</code>
     */
    public Builder setNameKr(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      nameKr_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *字体韩语名
     * </pre>
     *
     * <code>string name_kr = 7;</code>
     */
    public Builder clearNameKr() {
      
      nameKr_ = getDefaultInstance().getNameKr();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *字体韩语名
     * </pre>
     *
     * <code>string name_kr = 7;</code>
     */
    public Builder setNameKrBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      nameKr_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object introEn_ = "";
    /**
     * <pre>
     *英语厂商介绍
     * </pre>
     *
     * <code>string intro_en = 8;</code>
     */
    public java.lang.String getIntroEn() {
      java.lang.Object ref = introEn_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        introEn_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *英语厂商介绍
     * </pre>
     *
     * <code>string intro_en = 8;</code>
     */
    public com.google.protobuf.ByteString
        getIntroEnBytes() {
      java.lang.Object ref = introEn_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        introEn_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *英语厂商介绍
     * </pre>
     *
     * <code>string intro_en = 8;</code>
     */
    public Builder setIntroEn(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      introEn_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *英语厂商介绍
     * </pre>
     *
     * <code>string intro_en = 8;</code>
     */
    public Builder clearIntroEn() {
      
      introEn_ = getDefaultInstance().getIntroEn();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *英语厂商介绍
     * </pre>
     *
     * <code>string intro_en = 8;</code>
     */
    public Builder setIntroEnBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      introEn_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object introCn_ = "";
    /**
     * <pre>
     *中文介绍
     * </pre>
     *
     * <code>string intro_cn = 9;</code>
     */
    public java.lang.String getIntroCn() {
      java.lang.Object ref = introCn_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        introCn_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *中文介绍
     * </pre>
     *
     * <code>string intro_cn = 9;</code>
     */
    public com.google.protobuf.ByteString
        getIntroCnBytes() {
      java.lang.Object ref = introCn_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        introCn_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *中文介绍
     * </pre>
     *
     * <code>string intro_cn = 9;</code>
     */
    public Builder setIntroCn(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      introCn_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *中文介绍
     * </pre>
     *
     * <code>string intro_cn = 9;</code>
     */
    public Builder clearIntroCn() {
      
      introCn_ = getDefaultInstance().getIntroCn();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *中文介绍
     * </pre>
     *
     * <code>string intro_cn = 9;</code>
     */
    public Builder setIntroCnBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      introCn_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object introTw_ = "";
    /**
     * <pre>
     *繁体中文介绍
     * </pre>
     *
     * <code>string intro_tw = 10;</code>
     */
    public java.lang.String getIntroTw() {
      java.lang.Object ref = introTw_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        introTw_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *繁体中文介绍
     * </pre>
     *
     * <code>string intro_tw = 10;</code>
     */
    public com.google.protobuf.ByteString
        getIntroTwBytes() {
      java.lang.Object ref = introTw_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        introTw_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *繁体中文介绍
     * </pre>
     *
     * <code>string intro_tw = 10;</code>
     */
    public Builder setIntroTw(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      introTw_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *繁体中文介绍
     * </pre>
     *
     * <code>string intro_tw = 10;</code>
     */
    public Builder clearIntroTw() {
      
      introTw_ = getDefaultInstance().getIntroTw();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *繁体中文介绍
     * </pre>
     *
     * <code>string intro_tw = 10;</code>
     */
    public Builder setIntroTwBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      introTw_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object introJp_ = "";
    /**
     * <pre>
     *日语介绍
     * </pre>
     *
     * <code>string intro_jp = 11;</code>
     */
    public java.lang.String getIntroJp() {
      java.lang.Object ref = introJp_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        introJp_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *日语介绍
     * </pre>
     *
     * <code>string intro_jp = 11;</code>
     */
    public com.google.protobuf.ByteString
        getIntroJpBytes() {
      java.lang.Object ref = introJp_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        introJp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *日语介绍
     * </pre>
     *
     * <code>string intro_jp = 11;</code>
     */
    public Builder setIntroJp(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      introJp_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *日语介绍
     * </pre>
     *
     * <code>string intro_jp = 11;</code>
     */
    public Builder clearIntroJp() {
      
      introJp_ = getDefaultInstance().getIntroJp();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *日语介绍
     * </pre>
     *
     * <code>string intro_jp = 11;</code>
     */
    public Builder setIntroJpBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      introJp_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object introKr_ = "";
    /**
     * <pre>
     *韩语介绍
     * </pre>
     *
     * <code>string intro_kr = 12;</code>
     */
    public java.lang.String getIntroKr() {
      java.lang.Object ref = introKr_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        introKr_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *韩语介绍
     * </pre>
     *
     * <code>string intro_kr = 12;</code>
     */
    public com.google.protobuf.ByteString
        getIntroKrBytes() {
      java.lang.Object ref = introKr_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        introKr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *韩语介绍
     * </pre>
     *
     * <code>string intro_kr = 12;</code>
     */
    public Builder setIntroKr(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      introKr_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *韩语介绍
     * </pre>
     *
     * <code>string intro_kr = 12;</code>
     */
    public Builder clearIntroKr() {
      
      introKr_ = getDefaultInstance().getIntroKr();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *韩语介绍
     * </pre>
     *
     * <code>string intro_kr = 12;</code>
     */
    public Builder setIntroKrBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      introKr_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:webfontsdk.FontMaker)
  }

  // @@protoc_insertion_point(class_scope:webfontsdk.FontMaker)
  private static final io.grpc.sdk.webfont.FontMaker DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.grpc.sdk.webfont.FontMaker();
  }

  public static io.grpc.sdk.webfont.FontMaker getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FontMaker>
      PARSER = new com.google.protobuf.AbstractParser<FontMaker>() {
    @java.lang.Override
    public FontMaker parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FontMaker(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FontMaker> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FontMaker> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.grpc.sdk.webfont.FontMaker getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

