// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: webfont.proto

package io.grpc.sdk.webfont;

/**
 * <pre>
 *字体信息
 * </pre>
 *
 * Protobuf type {@code webfontsdk.FontMetaInfo}
 */
public  final class FontMetaInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:webfontsdk.FontMetaInfo)
    FontMetaInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FontMetaInfo.newBuilder() to construct.
  private FontMetaInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FontMetaInfo() {
    nameEn_ = "";
    nameCn_ = "";
    nameTw_ = "";
    nameJp_ = "";
    nameKr_ = "";
    introEn_ = "";
    introCn_ = "";
    introTw_ = "";
    introJp_ = "";
    introKr_ = "";
    lang_ = java.util.Collections.emptyList();
    crUrlOnMakersite_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new FontMetaInfo();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FontMetaInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            fontId_ = input.readUInt32();
            break;
          }
          case 16: {

            makerId_ = input.readUInt32();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            nameEn_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            nameCn_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            nameTw_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            nameJp_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            nameKr_ = s;
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            introEn_ = s;
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();

            introCn_ = s;
            break;
          }
          case 82: {
            java.lang.String s = input.readStringRequireUtf8();

            introTw_ = s;
            break;
          }
          case 90: {
            java.lang.String s = input.readStringRequireUtf8();

            introJp_ = s;
            break;
          }
          case 98: {
            java.lang.String s = input.readStringRequireUtf8();

            introKr_ = s;
            break;
          }
          case 104: {
            int rawValue = input.readEnum();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              lang_ = new java.util.ArrayList<java.lang.Integer>();
              mutable_bitField0_ |= 0x00000001;
            }
            lang_.add(rawValue);
            break;
          }
          case 106: {
            int length = input.readRawVarint32();
            int oldLimit = input.pushLimit(length);
            while(input.getBytesUntilLimit() > 0) {
              int rawValue = input.readEnum();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                lang_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              lang_.add(rawValue);
            }
            input.popLimit(oldLimit);
            break;
          }
          case 112: {

            crPriceMonth_ = input.readInt32();
            break;
          }
          case 120: {

            crPriceYear_ = input.readInt32();
            break;
          }
          case 128: {

            crPriceCssdownload_ = input.readInt32();
            break;
          }
          case 136: {

            cdnFree_ = input.readBool();
            break;
          }
          case 144: {

            crBuyOnMakersite_ = input.readBool();
            break;
          }
          case 154: {
            java.lang.String s = input.readStringRequireUtf8();

            crUrlOnMakersite_ = s;
            break;
          }
          case 160: {

            serviceFeeOfOnlineMonth_ = input.readUInt32();
            break;
          }
          case 168: {

            serviceFeeOfOnlineYear_ = input.readUInt32();
            break;
          }
          case 176: {

            serviceFeeOfAttorneyMonth_ = input.readInt32();
            break;
          }
          case 184: {

            serviceFeeOfAttorneyYear_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        lang_ = java.util.Collections.unmodifiableList(lang_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.grpc.sdk.webfont.WebfontProto.internal_static_webfontsdk_FontMetaInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.grpc.sdk.webfont.WebfontProto.internal_static_webfontsdk_FontMetaInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.grpc.sdk.webfont.FontMetaInfo.class, io.grpc.sdk.webfont.FontMetaInfo.Builder.class);
  }

  public static final int FONT_ID_FIELD_NUMBER = 1;
  private int fontId_;
  /**
   * <pre>
   *字体id
   * </pre>
   *
   * <code>uint32 font_id = 1;</code>
   */
  public int getFontId() {
    return fontId_;
  }

  public static final int MAKER_ID_FIELD_NUMBER = 2;
  private int makerId_;
  /**
   * <pre>
   *厂商编号
   * </pre>
   *
   * <code>uint32 maker_id = 2;</code>
   */
  public int getMakerId() {
    return makerId_;
  }

  public static final int NAME_EN_FIELD_NUMBER = 3;
  private volatile java.lang.Object nameEn_;
  /**
   * <pre>
   *字体英文名
   * </pre>
   *
   * <code>string name_en = 3;</code>
   */
  public java.lang.String getNameEn() {
    java.lang.Object ref = nameEn_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      nameEn_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *字体英文名
   * </pre>
   *
   * <code>string name_en = 3;</code>
   */
  public com.google.protobuf.ByteString
      getNameEnBytes() {
    java.lang.Object ref = nameEn_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      nameEn_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_CN_FIELD_NUMBER = 4;
  private volatile java.lang.Object nameCn_;
  /**
   * <pre>
   *字体中文名
   * </pre>
   *
   * <code>string name_cn = 4;</code>
   */
  public java.lang.String getNameCn() {
    java.lang.Object ref = nameCn_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      nameCn_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *字体中文名
   * </pre>
   *
   * <code>string name_cn = 4;</code>
   */
  public com.google.protobuf.ByteString
      getNameCnBytes() {
    java.lang.Object ref = nameCn_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      nameCn_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_TW_FIELD_NUMBER = 5;
  private volatile java.lang.Object nameTw_;
  /**
   * <pre>
   *字体繁体名
   * </pre>
   *
   * <code>string name_tw = 5;</code>
   */
  public java.lang.String getNameTw() {
    java.lang.Object ref = nameTw_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      nameTw_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *字体繁体名
   * </pre>
   *
   * <code>string name_tw = 5;</code>
   */
  public com.google.protobuf.ByteString
      getNameTwBytes() {
    java.lang.Object ref = nameTw_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      nameTw_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_JP_FIELD_NUMBER = 6;
  private volatile java.lang.Object nameJp_;
  /**
   * <pre>
   *字体日文名
   * </pre>
   *
   * <code>string name_jp = 6;</code>
   */
  public java.lang.String getNameJp() {
    java.lang.Object ref = nameJp_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      nameJp_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *字体日文名
   * </pre>
   *
   * <code>string name_jp = 6;</code>
   */
  public com.google.protobuf.ByteString
      getNameJpBytes() {
    java.lang.Object ref = nameJp_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      nameJp_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_KR_FIELD_NUMBER = 7;
  private volatile java.lang.Object nameKr_;
  /**
   * <pre>
   *字体韩语名
   * </pre>
   *
   * <code>string name_kr = 7;</code>
   */
  public java.lang.String getNameKr() {
    java.lang.Object ref = nameKr_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      nameKr_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *字体韩语名
   * </pre>
   *
   * <code>string name_kr = 7;</code>
   */
  public com.google.protobuf.ByteString
      getNameKrBytes() {
    java.lang.Object ref = nameKr_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      nameKr_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INTRO_EN_FIELD_NUMBER = 8;
  private volatile java.lang.Object introEn_;
  /**
   * <pre>
   *英语介绍
   * </pre>
   *
   * <code>string intro_en = 8;</code>
   */
  public java.lang.String getIntroEn() {
    java.lang.Object ref = introEn_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      introEn_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *英语介绍
   * </pre>
   *
   * <code>string intro_en = 8;</code>
   */
  public com.google.protobuf.ByteString
      getIntroEnBytes() {
    java.lang.Object ref = introEn_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      introEn_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INTRO_CN_FIELD_NUMBER = 9;
  private volatile java.lang.Object introCn_;
  /**
   * <pre>
   *中文介绍
   * </pre>
   *
   * <code>string intro_cn = 9;</code>
   */
  public java.lang.String getIntroCn() {
    java.lang.Object ref = introCn_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      introCn_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *中文介绍
   * </pre>
   *
   * <code>string intro_cn = 9;</code>
   */
  public com.google.protobuf.ByteString
      getIntroCnBytes() {
    java.lang.Object ref = introCn_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      introCn_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INTRO_TW_FIELD_NUMBER = 10;
  private volatile java.lang.Object introTw_;
  /**
   * <pre>
   *繁体中文介绍
   * </pre>
   *
   * <code>string intro_tw = 10;</code>
   */
  public java.lang.String getIntroTw() {
    java.lang.Object ref = introTw_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      introTw_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *繁体中文介绍
   * </pre>
   *
   * <code>string intro_tw = 10;</code>
   */
  public com.google.protobuf.ByteString
      getIntroTwBytes() {
    java.lang.Object ref = introTw_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      introTw_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INTRO_JP_FIELD_NUMBER = 11;
  private volatile java.lang.Object introJp_;
  /**
   * <pre>
   *日语介绍
   * </pre>
   *
   * <code>string intro_jp = 11;</code>
   */
  public java.lang.String getIntroJp() {
    java.lang.Object ref = introJp_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      introJp_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *日语介绍
   * </pre>
   *
   * <code>string intro_jp = 11;</code>
   */
  public com.google.protobuf.ByteString
      getIntroJpBytes() {
    java.lang.Object ref = introJp_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      introJp_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INTRO_KR_FIELD_NUMBER = 12;
  private volatile java.lang.Object introKr_;
  /**
   * <pre>
   *韩语介绍
   * </pre>
   *
   * <code>string intro_kr = 12;</code>
   */
  public java.lang.String getIntroKr() {
    java.lang.Object ref = introKr_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      introKr_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *韩语介绍
   * </pre>
   *
   * <code>string intro_kr = 12;</code>
   */
  public com.google.protobuf.ByteString
      getIntroKrBytes() {
    java.lang.Object ref = introKr_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      introKr_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LANG_FIELD_NUMBER = 13;
  private java.util.List<java.lang.Integer> lang_;
  private static final com.google.protobuf.Internal.ListAdapter.Converter<
      java.lang.Integer, io.grpc.sdk.webfont.Language> lang_converter_ =
          new com.google.protobuf.Internal.ListAdapter.Converter<
              java.lang.Integer, io.grpc.sdk.webfont.Language>() {
            public io.grpc.sdk.webfont.Language convert(java.lang.Integer from) {
              @SuppressWarnings("deprecation")
              io.grpc.sdk.webfont.Language result = io.grpc.sdk.webfont.Language.valueOf(from);
              return result == null ? io.grpc.sdk.webfont.Language.UNRECOGNIZED : result;
            }
          };
  /**
   * <pre>
   *语系列表
   * </pre>
   *
   * <code>repeated .webfontsdk.Language lang = 13;</code>
   */
  public java.util.List<io.grpc.sdk.webfont.Language> getLangList() {
    return new com.google.protobuf.Internal.ListAdapter<
        java.lang.Integer, io.grpc.sdk.webfont.Language>(lang_, lang_converter_);
  }
  /**
   * <pre>
   *语系列表
   * </pre>
   *
   * <code>repeated .webfontsdk.Language lang = 13;</code>
   */
  public int getLangCount() {
    return lang_.size();
  }
  /**
   * <pre>
   *语系列表
   * </pre>
   *
   * <code>repeated .webfontsdk.Language lang = 13;</code>
   */
  public io.grpc.sdk.webfont.Language getLang(int index) {
    return lang_converter_.convert(lang_.get(index));
  }
  /**
   * <pre>
   *语系列表
   * </pre>
   *
   * <code>repeated .webfontsdk.Language lang = 13;</code>
   */
  public java.util.List<java.lang.Integer>
  getLangValueList() {
    return lang_;
  }
  /**
   * <pre>
   *语系列表
   * </pre>
   *
   * <code>repeated .webfontsdk.Language lang = 13;</code>
   */
  public int getLangValue(int index) {
    return lang_.get(index);
  }
  private int langMemoizedSerializedSize;

  public static final int CR_PRICE_MONTH_FIELD_NUMBER = 14;
  private int crPriceMonth_;
  /**
   * <pre>
   *版权授权价格：0代表免费，-1代表不允许按月购买
   * </pre>
   *
   * <code>int32 cr_price_month = 14;</code>
   */
  public int getCrPriceMonth() {
    return crPriceMonth_;
  }

  public static final int CR_PRICE_YEAR_FIELD_NUMBER = 15;
  private int crPriceYear_;
  /**
   * <pre>
   *版权按年价格：0代表免费，-1代表不允许按年购买，都为-1则无法提供在线购买方式，
   * </pre>
   *
   * <code>int32 cr_price_year = 15;</code>
   */
  public int getCrPriceYear() {
    return crPriceYear_;
  }

  public static final int CR_PRICE_CSSDOWNLOAD_FIELD_NUMBER = 16;
  private int crPriceCssdownload_;
  /**
   * <pre>
   *CSS文件下载价格,按次收费。298元左右,-1代表不允许下载css，0代表免费
   * </pre>
   *
   * <code>int32 cr_price_cssdownload = 16;</code>
   */
  public int getCrPriceCssdownload() {
    return crPriceCssdownload_;
  }

  public static final int CDN_FREE_FIELD_NUMBER = 17;
  private boolean cdnFree_;
  /**
   * <pre>
   *是否免cdn流量费
   * </pre>
   *
   * <code>bool cdn_free = 17;</code>
   */
  public boolean getCdnFree() {
    return cdnFree_;
  }

  public static final int CR_BUY_ON_MAKERSITE_FIELD_NUMBER = 18;
  private boolean crBuyOnMakersite_;
  /**
   * <pre>
   *是否可以在厂商官网购买
   * </pre>
   *
   * <code>bool cr_buy_on_makersite = 18;</code>
   */
  public boolean getCrBuyOnMakersite() {
    return crBuyOnMakersite_;
  }

  public static final int CR_URL_ON_MAKERSITE_FIELD_NUMBER = 19;
  private volatile java.lang.Object crUrlOnMakersite_;
  /**
   * <pre>
   *当前字体在厂商的网址，如果为 "" 则自动使用厂商网址填充
   * </pre>
   *
   * <code>string cr_url_on_makersite = 19;</code>
   */
  public java.lang.String getCrUrlOnMakersite() {
    java.lang.Object ref = crUrlOnMakersite_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      crUrlOnMakersite_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *当前字体在厂商的网址，如果为 "" 则自动使用厂商网址填充
   * </pre>
   *
   * <code>string cr_url_on_makersite = 19;</code>
   */
  public com.google.protobuf.ByteString
      getCrUrlOnMakersiteBytes() {
    java.lang.Object ref = crUrlOnMakersite_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      crUrlOnMakersite_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SERVICE_FEE_OF_ONLINE_MONTH_FIELD_NUMBER = 20;
  private int serviceFeeOfOnlineMonth_;
  /**
   * <pre>
   *通过在线购买的月服务费  0代表免费
   * </pre>
   *
   * <code>uint32 service_fee_of_online_month = 20;</code>
   */
  public int getServiceFeeOfOnlineMonth() {
    return serviceFeeOfOnlineMonth_;
  }

  public static final int SERVICE_FEE_OF_ONLINE_YEAR_FIELD_NUMBER = 21;
  private int serviceFeeOfOnlineYear_;
  /**
   * <pre>
   *通过在线购买的年服务费   0代表免费
   * </pre>
   *
   * <code>uint32 service_fee_of_online_year = 21;</code>
   */
  public int getServiceFeeOfOnlineYear() {
    return serviceFeeOfOnlineYear_;
  }

  public static final int SERVICE_FEE_OF_ATTORNEY_MONTH_FIELD_NUMBER = 22;
  private int serviceFeeOfAttorneyMonth_;
  /**
   * <pre>
   *通过上传授权书购买的月服务费   -1代表不允许上传授权书  0代表免费
   * </pre>
   *
   * <code>int32 service_fee_of_attorney_month = 22;</code>
   */
  public int getServiceFeeOfAttorneyMonth() {
    return serviceFeeOfAttorneyMonth_;
  }

  public static final int SERVICE_FEE_OF_ATTORNEY_YEAR_FIELD_NUMBER = 23;
  private int serviceFeeOfAttorneyYear_;
  /**
   * <pre>
   *通过上传授权书购买的年服务费    -1代表不允许上传授权书  0代表免费
   * </pre>
   *
   * <code>int32 service_fee_of_attorney_year = 23;</code>
   */
  public int getServiceFeeOfAttorneyYear() {
    return serviceFeeOfAttorneyYear_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (fontId_ != 0) {
      output.writeUInt32(1, fontId_);
    }
    if (makerId_ != 0) {
      output.writeUInt32(2, makerId_);
    }
    if (!getNameEnBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, nameEn_);
    }
    if (!getNameCnBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, nameCn_);
    }
    if (!getNameTwBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, nameTw_);
    }
    if (!getNameJpBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, nameJp_);
    }
    if (!getNameKrBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, nameKr_);
    }
    if (!getIntroEnBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, introEn_);
    }
    if (!getIntroCnBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, introCn_);
    }
    if (!getIntroTwBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, introTw_);
    }
    if (!getIntroJpBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, introJp_);
    }
    if (!getIntroKrBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 12, introKr_);
    }
    if (getLangList().size() > 0) {
      output.writeUInt32NoTag(106);
      output.writeUInt32NoTag(langMemoizedSerializedSize);
    }
    for (int i = 0; i < lang_.size(); i++) {
      output.writeEnumNoTag(lang_.get(i));
    }
    if (crPriceMonth_ != 0) {
      output.writeInt32(14, crPriceMonth_);
    }
    if (crPriceYear_ != 0) {
      output.writeInt32(15, crPriceYear_);
    }
    if (crPriceCssdownload_ != 0) {
      output.writeInt32(16, crPriceCssdownload_);
    }
    if (cdnFree_ != false) {
      output.writeBool(17, cdnFree_);
    }
    if (crBuyOnMakersite_ != false) {
      output.writeBool(18, crBuyOnMakersite_);
    }
    if (!getCrUrlOnMakersiteBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 19, crUrlOnMakersite_);
    }
    if (serviceFeeOfOnlineMonth_ != 0) {
      output.writeUInt32(20, serviceFeeOfOnlineMonth_);
    }
    if (serviceFeeOfOnlineYear_ != 0) {
      output.writeUInt32(21, serviceFeeOfOnlineYear_);
    }
    if (serviceFeeOfAttorneyMonth_ != 0) {
      output.writeInt32(22, serviceFeeOfAttorneyMonth_);
    }
    if (serviceFeeOfAttorneyYear_ != 0) {
      output.writeInt32(23, serviceFeeOfAttorneyYear_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (fontId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, fontId_);
    }
    if (makerId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(2, makerId_);
    }
    if (!getNameEnBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, nameEn_);
    }
    if (!getNameCnBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, nameCn_);
    }
    if (!getNameTwBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, nameTw_);
    }
    if (!getNameJpBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, nameJp_);
    }
    if (!getNameKrBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, nameKr_);
    }
    if (!getIntroEnBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, introEn_);
    }
    if (!getIntroCnBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, introCn_);
    }
    if (!getIntroTwBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, introTw_);
    }
    if (!getIntroJpBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, introJp_);
    }
    if (!getIntroKrBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, introKr_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < lang_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeEnumSizeNoTag(lang_.get(i));
      }
      size += dataSize;
      if (!getLangList().isEmpty()) {  size += 1;
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32SizeNoTag(dataSize);
      }langMemoizedSerializedSize = dataSize;
    }
    if (crPriceMonth_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(14, crPriceMonth_);
    }
    if (crPriceYear_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(15, crPriceYear_);
    }
    if (crPriceCssdownload_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(16, crPriceCssdownload_);
    }
    if (cdnFree_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(17, cdnFree_);
    }
    if (crBuyOnMakersite_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(18, crBuyOnMakersite_);
    }
    if (!getCrUrlOnMakersiteBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(19, crUrlOnMakersite_);
    }
    if (serviceFeeOfOnlineMonth_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(20, serviceFeeOfOnlineMonth_);
    }
    if (serviceFeeOfOnlineYear_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(21, serviceFeeOfOnlineYear_);
    }
    if (serviceFeeOfAttorneyMonth_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(22, serviceFeeOfAttorneyMonth_);
    }
    if (serviceFeeOfAttorneyYear_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(23, serviceFeeOfAttorneyYear_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.grpc.sdk.webfont.FontMetaInfo)) {
      return super.equals(obj);
    }
    io.grpc.sdk.webfont.FontMetaInfo other = (io.grpc.sdk.webfont.FontMetaInfo) obj;

    if (getFontId()
        != other.getFontId()) return false;
    if (getMakerId()
        != other.getMakerId()) return false;
    if (!getNameEn()
        .equals(other.getNameEn())) return false;
    if (!getNameCn()
        .equals(other.getNameCn())) return false;
    if (!getNameTw()
        .equals(other.getNameTw())) return false;
    if (!getNameJp()
        .equals(other.getNameJp())) return false;
    if (!getNameKr()
        .equals(other.getNameKr())) return false;
    if (!getIntroEn()
        .equals(other.getIntroEn())) return false;
    if (!getIntroCn()
        .equals(other.getIntroCn())) return false;
    if (!getIntroTw()
        .equals(other.getIntroTw())) return false;
    if (!getIntroJp()
        .equals(other.getIntroJp())) return false;
    if (!getIntroKr()
        .equals(other.getIntroKr())) return false;
    if (!lang_.equals(other.lang_)) return false;
    if (getCrPriceMonth()
        != other.getCrPriceMonth()) return false;
    if (getCrPriceYear()
        != other.getCrPriceYear()) return false;
    if (getCrPriceCssdownload()
        != other.getCrPriceCssdownload()) return false;
    if (getCdnFree()
        != other.getCdnFree()) return false;
    if (getCrBuyOnMakersite()
        != other.getCrBuyOnMakersite()) return false;
    if (!getCrUrlOnMakersite()
        .equals(other.getCrUrlOnMakersite())) return false;
    if (getServiceFeeOfOnlineMonth()
        != other.getServiceFeeOfOnlineMonth()) return false;
    if (getServiceFeeOfOnlineYear()
        != other.getServiceFeeOfOnlineYear()) return false;
    if (getServiceFeeOfAttorneyMonth()
        != other.getServiceFeeOfAttorneyMonth()) return false;
    if (getServiceFeeOfAttorneyYear()
        != other.getServiceFeeOfAttorneyYear()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + FONT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getFontId();
    hash = (37 * hash) + MAKER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getMakerId();
    hash = (37 * hash) + NAME_EN_FIELD_NUMBER;
    hash = (53 * hash) + getNameEn().hashCode();
    hash = (37 * hash) + NAME_CN_FIELD_NUMBER;
    hash = (53 * hash) + getNameCn().hashCode();
    hash = (37 * hash) + NAME_TW_FIELD_NUMBER;
    hash = (53 * hash) + getNameTw().hashCode();
    hash = (37 * hash) + NAME_JP_FIELD_NUMBER;
    hash = (53 * hash) + getNameJp().hashCode();
    hash = (37 * hash) + NAME_KR_FIELD_NUMBER;
    hash = (53 * hash) + getNameKr().hashCode();
    hash = (37 * hash) + INTRO_EN_FIELD_NUMBER;
    hash = (53 * hash) + getIntroEn().hashCode();
    hash = (37 * hash) + INTRO_CN_FIELD_NUMBER;
    hash = (53 * hash) + getIntroCn().hashCode();
    hash = (37 * hash) + INTRO_TW_FIELD_NUMBER;
    hash = (53 * hash) + getIntroTw().hashCode();
    hash = (37 * hash) + INTRO_JP_FIELD_NUMBER;
    hash = (53 * hash) + getIntroJp().hashCode();
    hash = (37 * hash) + INTRO_KR_FIELD_NUMBER;
    hash = (53 * hash) + getIntroKr().hashCode();
    if (getLangCount() > 0) {
      hash = (37 * hash) + LANG_FIELD_NUMBER;
      hash = (53 * hash) + lang_.hashCode();
    }
    hash = (37 * hash) + CR_PRICE_MONTH_FIELD_NUMBER;
    hash = (53 * hash) + getCrPriceMonth();
    hash = (37 * hash) + CR_PRICE_YEAR_FIELD_NUMBER;
    hash = (53 * hash) + getCrPriceYear();
    hash = (37 * hash) + CR_PRICE_CSSDOWNLOAD_FIELD_NUMBER;
    hash = (53 * hash) + getCrPriceCssdownload();
    hash = (37 * hash) + CDN_FREE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getCdnFree());
    hash = (37 * hash) + CR_BUY_ON_MAKERSITE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getCrBuyOnMakersite());
    hash = (37 * hash) + CR_URL_ON_MAKERSITE_FIELD_NUMBER;
    hash = (53 * hash) + getCrUrlOnMakersite().hashCode();
    hash = (37 * hash) + SERVICE_FEE_OF_ONLINE_MONTH_FIELD_NUMBER;
    hash = (53 * hash) + getServiceFeeOfOnlineMonth();
    hash = (37 * hash) + SERVICE_FEE_OF_ONLINE_YEAR_FIELD_NUMBER;
    hash = (53 * hash) + getServiceFeeOfOnlineYear();
    hash = (37 * hash) + SERVICE_FEE_OF_ATTORNEY_MONTH_FIELD_NUMBER;
    hash = (53 * hash) + getServiceFeeOfAttorneyMonth();
    hash = (37 * hash) + SERVICE_FEE_OF_ATTORNEY_YEAR_FIELD_NUMBER;
    hash = (53 * hash) + getServiceFeeOfAttorneyYear();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.grpc.sdk.webfont.FontMetaInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.grpc.sdk.webfont.FontMetaInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.grpc.sdk.webfont.FontMetaInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.grpc.sdk.webfont.FontMetaInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.grpc.sdk.webfont.FontMetaInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.grpc.sdk.webfont.FontMetaInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.grpc.sdk.webfont.FontMetaInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.grpc.sdk.webfont.FontMetaInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.grpc.sdk.webfont.FontMetaInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.grpc.sdk.webfont.FontMetaInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.grpc.sdk.webfont.FontMetaInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.grpc.sdk.webfont.FontMetaInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.grpc.sdk.webfont.FontMetaInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *字体信息
   * </pre>
   *
   * Protobuf type {@code webfontsdk.FontMetaInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:webfontsdk.FontMetaInfo)
      io.grpc.sdk.webfont.FontMetaInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.grpc.sdk.webfont.WebfontProto.internal_static_webfontsdk_FontMetaInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.grpc.sdk.webfont.WebfontProto.internal_static_webfontsdk_FontMetaInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.grpc.sdk.webfont.FontMetaInfo.class, io.grpc.sdk.webfont.FontMetaInfo.Builder.class);
    }

    // Construct using io.grpc.sdk.webfont.FontMetaInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      fontId_ = 0;

      makerId_ = 0;

      nameEn_ = "";

      nameCn_ = "";

      nameTw_ = "";

      nameJp_ = "";

      nameKr_ = "";

      introEn_ = "";

      introCn_ = "";

      introTw_ = "";

      introJp_ = "";

      introKr_ = "";

      lang_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);
      crPriceMonth_ = 0;

      crPriceYear_ = 0;

      crPriceCssdownload_ = 0;

      cdnFree_ = false;

      crBuyOnMakersite_ = false;

      crUrlOnMakersite_ = "";

      serviceFeeOfOnlineMonth_ = 0;

      serviceFeeOfOnlineYear_ = 0;

      serviceFeeOfAttorneyMonth_ = 0;

      serviceFeeOfAttorneyYear_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.grpc.sdk.webfont.WebfontProto.internal_static_webfontsdk_FontMetaInfo_descriptor;
    }

    @java.lang.Override
    public io.grpc.sdk.webfont.FontMetaInfo getDefaultInstanceForType() {
      return io.grpc.sdk.webfont.FontMetaInfo.getDefaultInstance();
    }

    @java.lang.Override
    public io.grpc.sdk.webfont.FontMetaInfo build() {
      io.grpc.sdk.webfont.FontMetaInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.grpc.sdk.webfont.FontMetaInfo buildPartial() {
      io.grpc.sdk.webfont.FontMetaInfo result = new io.grpc.sdk.webfont.FontMetaInfo(this);
      int from_bitField0_ = bitField0_;
      result.fontId_ = fontId_;
      result.makerId_ = makerId_;
      result.nameEn_ = nameEn_;
      result.nameCn_ = nameCn_;
      result.nameTw_ = nameTw_;
      result.nameJp_ = nameJp_;
      result.nameKr_ = nameKr_;
      result.introEn_ = introEn_;
      result.introCn_ = introCn_;
      result.introTw_ = introTw_;
      result.introJp_ = introJp_;
      result.introKr_ = introKr_;
      if (((bitField0_ & 0x00000001) != 0)) {
        lang_ = java.util.Collections.unmodifiableList(lang_);
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.lang_ = lang_;
      result.crPriceMonth_ = crPriceMonth_;
      result.crPriceYear_ = crPriceYear_;
      result.crPriceCssdownload_ = crPriceCssdownload_;
      result.cdnFree_ = cdnFree_;
      result.crBuyOnMakersite_ = crBuyOnMakersite_;
      result.crUrlOnMakersite_ = crUrlOnMakersite_;
      result.serviceFeeOfOnlineMonth_ = serviceFeeOfOnlineMonth_;
      result.serviceFeeOfOnlineYear_ = serviceFeeOfOnlineYear_;
      result.serviceFeeOfAttorneyMonth_ = serviceFeeOfAttorneyMonth_;
      result.serviceFeeOfAttorneyYear_ = serviceFeeOfAttorneyYear_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.grpc.sdk.webfont.FontMetaInfo) {
        return mergeFrom((io.grpc.sdk.webfont.FontMetaInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.grpc.sdk.webfont.FontMetaInfo other) {
      if (other == io.grpc.sdk.webfont.FontMetaInfo.getDefaultInstance()) return this;
      if (other.getFontId() != 0) {
        setFontId(other.getFontId());
      }
      if (other.getMakerId() != 0) {
        setMakerId(other.getMakerId());
      }
      if (!other.getNameEn().isEmpty()) {
        nameEn_ = other.nameEn_;
        onChanged();
      }
      if (!other.getNameCn().isEmpty()) {
        nameCn_ = other.nameCn_;
        onChanged();
      }
      if (!other.getNameTw().isEmpty()) {
        nameTw_ = other.nameTw_;
        onChanged();
      }
      if (!other.getNameJp().isEmpty()) {
        nameJp_ = other.nameJp_;
        onChanged();
      }
      if (!other.getNameKr().isEmpty()) {
        nameKr_ = other.nameKr_;
        onChanged();
      }
      if (!other.getIntroEn().isEmpty()) {
        introEn_ = other.introEn_;
        onChanged();
      }
      if (!other.getIntroCn().isEmpty()) {
        introCn_ = other.introCn_;
        onChanged();
      }
      if (!other.getIntroTw().isEmpty()) {
        introTw_ = other.introTw_;
        onChanged();
      }
      if (!other.getIntroJp().isEmpty()) {
        introJp_ = other.introJp_;
        onChanged();
      }
      if (!other.getIntroKr().isEmpty()) {
        introKr_ = other.introKr_;
        onChanged();
      }
      if (!other.lang_.isEmpty()) {
        if (lang_.isEmpty()) {
          lang_ = other.lang_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureLangIsMutable();
          lang_.addAll(other.lang_);
        }
        onChanged();
      }
      if (other.getCrPriceMonth() != 0) {
        setCrPriceMonth(other.getCrPriceMonth());
      }
      if (other.getCrPriceYear() != 0) {
        setCrPriceYear(other.getCrPriceYear());
      }
      if (other.getCrPriceCssdownload() != 0) {
        setCrPriceCssdownload(other.getCrPriceCssdownload());
      }
      if (other.getCdnFree() != false) {
        setCdnFree(other.getCdnFree());
      }
      if (other.getCrBuyOnMakersite() != false) {
        setCrBuyOnMakersite(other.getCrBuyOnMakersite());
      }
      if (!other.getCrUrlOnMakersite().isEmpty()) {
        crUrlOnMakersite_ = other.crUrlOnMakersite_;
        onChanged();
      }
      if (other.getServiceFeeOfOnlineMonth() != 0) {
        setServiceFeeOfOnlineMonth(other.getServiceFeeOfOnlineMonth());
      }
      if (other.getServiceFeeOfOnlineYear() != 0) {
        setServiceFeeOfOnlineYear(other.getServiceFeeOfOnlineYear());
      }
      if (other.getServiceFeeOfAttorneyMonth() != 0) {
        setServiceFeeOfAttorneyMonth(other.getServiceFeeOfAttorneyMonth());
      }
      if (other.getServiceFeeOfAttorneyYear() != 0) {
        setServiceFeeOfAttorneyYear(other.getServiceFeeOfAttorneyYear());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.grpc.sdk.webfont.FontMetaInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.grpc.sdk.webfont.FontMetaInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int fontId_ ;
    /**
     * <pre>
     *字体id
     * </pre>
     *
     * <code>uint32 font_id = 1;</code>
     */
    public int getFontId() {
      return fontId_;
    }
    /**
     * <pre>
     *字体id
     * </pre>
     *
     * <code>uint32 font_id = 1;</code>
     */
    public Builder setFontId(int value) {
      
      fontId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *字体id
     * </pre>
     *
     * <code>uint32 font_id = 1;</code>
     */
    public Builder clearFontId() {
      
      fontId_ = 0;
      onChanged();
      return this;
    }

    private int makerId_ ;
    /**
     * <pre>
     *厂商编号
     * </pre>
     *
     * <code>uint32 maker_id = 2;</code>
     */
    public int getMakerId() {
      return makerId_;
    }
    /**
     * <pre>
     *厂商编号
     * </pre>
     *
     * <code>uint32 maker_id = 2;</code>
     */
    public Builder setMakerId(int value) {
      
      makerId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *厂商编号
     * </pre>
     *
     * <code>uint32 maker_id = 2;</code>
     */
    public Builder clearMakerId() {
      
      makerId_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object nameEn_ = "";
    /**
     * <pre>
     *字体英文名
     * </pre>
     *
     * <code>string name_en = 3;</code>
     */
    public java.lang.String getNameEn() {
      java.lang.Object ref = nameEn_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nameEn_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *字体英文名
     * </pre>
     *
     * <code>string name_en = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNameEnBytes() {
      java.lang.Object ref = nameEn_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nameEn_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *字体英文名
     * </pre>
     *
     * <code>string name_en = 3;</code>
     */
    public Builder setNameEn(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      nameEn_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *字体英文名
     * </pre>
     *
     * <code>string name_en = 3;</code>
     */
    public Builder clearNameEn() {
      
      nameEn_ = getDefaultInstance().getNameEn();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *字体英文名
     * </pre>
     *
     * <code>string name_en = 3;</code>
     */
    public Builder setNameEnBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      nameEn_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object nameCn_ = "";
    /**
     * <pre>
     *字体中文名
     * </pre>
     *
     * <code>string name_cn = 4;</code>
     */
    public java.lang.String getNameCn() {
      java.lang.Object ref = nameCn_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nameCn_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *字体中文名
     * </pre>
     *
     * <code>string name_cn = 4;</code>
     */
    public com.google.protobuf.ByteString
        getNameCnBytes() {
      java.lang.Object ref = nameCn_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nameCn_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *字体中文名
     * </pre>
     *
     * <code>string name_cn = 4;</code>
     */
    public Builder setNameCn(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      nameCn_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *字体中文名
     * </pre>
     *
     * <code>string name_cn = 4;</code>
     */
    public Builder clearNameCn() {
      
      nameCn_ = getDefaultInstance().getNameCn();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *字体中文名
     * </pre>
     *
     * <code>string name_cn = 4;</code>
     */
    public Builder setNameCnBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      nameCn_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object nameTw_ = "";
    /**
     * <pre>
     *字体繁体名
     * </pre>
     *
     * <code>string name_tw = 5;</code>
     */
    public java.lang.String getNameTw() {
      java.lang.Object ref = nameTw_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nameTw_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *字体繁体名
     * </pre>
     *
     * <code>string name_tw = 5;</code>
     */
    public com.google.protobuf.ByteString
        getNameTwBytes() {
      java.lang.Object ref = nameTw_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nameTw_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *字体繁体名
     * </pre>
     *
     * <code>string name_tw = 5;</code>
     */
    public Builder setNameTw(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      nameTw_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *字体繁体名
     * </pre>
     *
     * <code>string name_tw = 5;</code>
     */
    public Builder clearNameTw() {
      
      nameTw_ = getDefaultInstance().getNameTw();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *字体繁体名
     * </pre>
     *
     * <code>string name_tw = 5;</code>
     */
    public Builder setNameTwBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      nameTw_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object nameJp_ = "";
    /**
     * <pre>
     *字体日文名
     * </pre>
     *
     * <code>string name_jp = 6;</code>
     */
    public java.lang.String getNameJp() {
      java.lang.Object ref = nameJp_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nameJp_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *字体日文名
     * </pre>
     *
     * <code>string name_jp = 6;</code>
     */
    public com.google.protobuf.ByteString
        getNameJpBytes() {
      java.lang.Object ref = nameJp_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nameJp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *字体日文名
     * </pre>
     *
     * <code>string name_jp = 6;</code>
     */
    public Builder setNameJp(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      nameJp_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *字体日文名
     * </pre>
     *
     * <code>string name_jp = 6;</code>
     */
    public Builder clearNameJp() {
      
      nameJp_ = getDefaultInstance().getNameJp();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *字体日文名
     * </pre>
     *
     * <code>string name_jp = 6;</code>
     */
    public Builder setNameJpBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      nameJp_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object nameKr_ = "";
    /**
     * <pre>
     *字体韩语名
     * </pre>
     *
     * <code>string name_kr = 7;</code>
     */
    public java.lang.String getNameKr() {
      java.lang.Object ref = nameKr_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nameKr_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *字体韩语名
     * </pre>
     *
     * <code>string name_kr = 7;</code>
     */
    public com.google.protobuf.ByteString
        getNameKrBytes() {
      java.lang.Object ref = nameKr_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nameKr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *字体韩语名
     * </pre>
     *
     * <code>string name_kr = 7;</code>
     */
    public Builder setNameKr(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      nameKr_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *字体韩语名
     * </pre>
     *
     * <code>string name_kr = 7;</code>
     */
    public Builder clearNameKr() {
      
      nameKr_ = getDefaultInstance().getNameKr();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *字体韩语名
     * </pre>
     *
     * <code>string name_kr = 7;</code>
     */
    public Builder setNameKrBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      nameKr_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object introEn_ = "";
    /**
     * <pre>
     *英语介绍
     * </pre>
     *
     * <code>string intro_en = 8;</code>
     */
    public java.lang.String getIntroEn() {
      java.lang.Object ref = introEn_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        introEn_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *英语介绍
     * </pre>
     *
     * <code>string intro_en = 8;</code>
     */
    public com.google.protobuf.ByteString
        getIntroEnBytes() {
      java.lang.Object ref = introEn_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        introEn_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *英语介绍
     * </pre>
     *
     * <code>string intro_en = 8;</code>
     */
    public Builder setIntroEn(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      introEn_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *英语介绍
     * </pre>
     *
     * <code>string intro_en = 8;</code>
     */
    public Builder clearIntroEn() {
      
      introEn_ = getDefaultInstance().getIntroEn();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *英语介绍
     * </pre>
     *
     * <code>string intro_en = 8;</code>
     */
    public Builder setIntroEnBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      introEn_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object introCn_ = "";
    /**
     * <pre>
     *中文介绍
     * </pre>
     *
     * <code>string intro_cn = 9;</code>
     */
    public java.lang.String getIntroCn() {
      java.lang.Object ref = introCn_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        introCn_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *中文介绍
     * </pre>
     *
     * <code>string intro_cn = 9;</code>
     */
    public com.google.protobuf.ByteString
        getIntroCnBytes() {
      java.lang.Object ref = introCn_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        introCn_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *中文介绍
     * </pre>
     *
     * <code>string intro_cn = 9;</code>
     */
    public Builder setIntroCn(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      introCn_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *中文介绍
     * </pre>
     *
     * <code>string intro_cn = 9;</code>
     */
    public Builder clearIntroCn() {
      
      introCn_ = getDefaultInstance().getIntroCn();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *中文介绍
     * </pre>
     *
     * <code>string intro_cn = 9;</code>
     */
    public Builder setIntroCnBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      introCn_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object introTw_ = "";
    /**
     * <pre>
     *繁体中文介绍
     * </pre>
     *
     * <code>string intro_tw = 10;</code>
     */
    public java.lang.String getIntroTw() {
      java.lang.Object ref = introTw_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        introTw_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *繁体中文介绍
     * </pre>
     *
     * <code>string intro_tw = 10;</code>
     */
    public com.google.protobuf.ByteString
        getIntroTwBytes() {
      java.lang.Object ref = introTw_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        introTw_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *繁体中文介绍
     * </pre>
     *
     * <code>string intro_tw = 10;</code>
     */
    public Builder setIntroTw(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      introTw_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *繁体中文介绍
     * </pre>
     *
     * <code>string intro_tw = 10;</code>
     */
    public Builder clearIntroTw() {
      
      introTw_ = getDefaultInstance().getIntroTw();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *繁体中文介绍
     * </pre>
     *
     * <code>string intro_tw = 10;</code>
     */
    public Builder setIntroTwBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      introTw_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object introJp_ = "";
    /**
     * <pre>
     *日语介绍
     * </pre>
     *
     * <code>string intro_jp = 11;</code>
     */
    public java.lang.String getIntroJp() {
      java.lang.Object ref = introJp_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        introJp_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *日语介绍
     * </pre>
     *
     * <code>string intro_jp = 11;</code>
     */
    public com.google.protobuf.ByteString
        getIntroJpBytes() {
      java.lang.Object ref = introJp_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        introJp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *日语介绍
     * </pre>
     *
     * <code>string intro_jp = 11;</code>
     */
    public Builder setIntroJp(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      introJp_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *日语介绍
     * </pre>
     *
     * <code>string intro_jp = 11;</code>
     */
    public Builder clearIntroJp() {
      
      introJp_ = getDefaultInstance().getIntroJp();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *日语介绍
     * </pre>
     *
     * <code>string intro_jp = 11;</code>
     */
    public Builder setIntroJpBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      introJp_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object introKr_ = "";
    /**
     * <pre>
     *韩语介绍
     * </pre>
     *
     * <code>string intro_kr = 12;</code>
     */
    public java.lang.String getIntroKr() {
      java.lang.Object ref = introKr_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        introKr_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *韩语介绍
     * </pre>
     *
     * <code>string intro_kr = 12;</code>
     */
    public com.google.protobuf.ByteString
        getIntroKrBytes() {
      java.lang.Object ref = introKr_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        introKr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *韩语介绍
     * </pre>
     *
     * <code>string intro_kr = 12;</code>
     */
    public Builder setIntroKr(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      introKr_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *韩语介绍
     * </pre>
     *
     * <code>string intro_kr = 12;</code>
     */
    public Builder clearIntroKr() {
      
      introKr_ = getDefaultInstance().getIntroKr();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *韩语介绍
     * </pre>
     *
     * <code>string intro_kr = 12;</code>
     */
    public Builder setIntroKrBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      introKr_ = value;
      onChanged();
      return this;
    }

    private java.util.List<java.lang.Integer> lang_ =
      java.util.Collections.emptyList();
    private void ensureLangIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        lang_ = new java.util.ArrayList<java.lang.Integer>(lang_);
        bitField0_ |= 0x00000001;
      }
    }
    /**
     * <pre>
     *语系列表
     * </pre>
     *
     * <code>repeated .webfontsdk.Language lang = 13;</code>
     */
    public java.util.List<io.grpc.sdk.webfont.Language> getLangList() {
      return new com.google.protobuf.Internal.ListAdapter<
          java.lang.Integer, io.grpc.sdk.webfont.Language>(lang_, lang_converter_);
    }
    /**
     * <pre>
     *语系列表
     * </pre>
     *
     * <code>repeated .webfontsdk.Language lang = 13;</code>
     */
    public int getLangCount() {
      return lang_.size();
    }
    /**
     * <pre>
     *语系列表
     * </pre>
     *
     * <code>repeated .webfontsdk.Language lang = 13;</code>
     */
    public io.grpc.sdk.webfont.Language getLang(int index) {
      return lang_converter_.convert(lang_.get(index));
    }
    /**
     * <pre>
     *语系列表
     * </pre>
     *
     * <code>repeated .webfontsdk.Language lang = 13;</code>
     */
    public Builder setLang(
        int index, io.grpc.sdk.webfont.Language value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureLangIsMutable();
      lang_.set(index, value.getNumber());
      onChanged();
      return this;
    }
    /**
     * <pre>
     *语系列表
     * </pre>
     *
     * <code>repeated .webfontsdk.Language lang = 13;</code>
     */
    public Builder addLang(io.grpc.sdk.webfont.Language value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureLangIsMutable();
      lang_.add(value.getNumber());
      onChanged();
      return this;
    }
    /**
     * <pre>
     *语系列表
     * </pre>
     *
     * <code>repeated .webfontsdk.Language lang = 13;</code>
     */
    public Builder addAllLang(
        java.lang.Iterable<? extends io.grpc.sdk.webfont.Language> values) {
      ensureLangIsMutable();
      for (io.grpc.sdk.webfont.Language value : values) {
        lang_.add(value.getNumber());
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     *语系列表
     * </pre>
     *
     * <code>repeated .webfontsdk.Language lang = 13;</code>
     */
    public Builder clearLang() {
      lang_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *语系列表
     * </pre>
     *
     * <code>repeated .webfontsdk.Language lang = 13;</code>
     */
    public java.util.List<java.lang.Integer>
    getLangValueList() {
      return java.util.Collections.unmodifiableList(lang_);
    }
    /**
     * <pre>
     *语系列表
     * </pre>
     *
     * <code>repeated .webfontsdk.Language lang = 13;</code>
     */
    public int getLangValue(int index) {
      return lang_.get(index);
    }
    /**
     * <pre>
     *语系列表
     * </pre>
     *
     * <code>repeated .webfontsdk.Language lang = 13;</code>
     */
    public Builder setLangValue(
        int index, int value) {
      ensureLangIsMutable();
      lang_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *语系列表
     * </pre>
     *
     * <code>repeated .webfontsdk.Language lang = 13;</code>
     */
    public Builder addLangValue(int value) {
      ensureLangIsMutable();
      lang_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *语系列表
     * </pre>
     *
     * <code>repeated .webfontsdk.Language lang = 13;</code>
     */
    public Builder addAllLangValue(
        java.lang.Iterable<java.lang.Integer> values) {
      ensureLangIsMutable();
      for (int value : values) {
        lang_.add(value);
      }
      onChanged();
      return this;
    }

    private int crPriceMonth_ ;
    /**
     * <pre>
     *版权授权价格：0代表免费，-1代表不允许按月购买
     * </pre>
     *
     * <code>int32 cr_price_month = 14;</code>
     */
    public int getCrPriceMonth() {
      return crPriceMonth_;
    }
    /**
     * <pre>
     *版权授权价格：0代表免费，-1代表不允许按月购买
     * </pre>
     *
     * <code>int32 cr_price_month = 14;</code>
     */
    public Builder setCrPriceMonth(int value) {
      
      crPriceMonth_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *版权授权价格：0代表免费，-1代表不允许按月购买
     * </pre>
     *
     * <code>int32 cr_price_month = 14;</code>
     */
    public Builder clearCrPriceMonth() {
      
      crPriceMonth_ = 0;
      onChanged();
      return this;
    }

    private int crPriceYear_ ;
    /**
     * <pre>
     *版权按年价格：0代表免费，-1代表不允许按年购买，都为-1则无法提供在线购买方式，
     * </pre>
     *
     * <code>int32 cr_price_year = 15;</code>
     */
    public int getCrPriceYear() {
      return crPriceYear_;
    }
    /**
     * <pre>
     *版权按年价格：0代表免费，-1代表不允许按年购买，都为-1则无法提供在线购买方式，
     * </pre>
     *
     * <code>int32 cr_price_year = 15;</code>
     */
    public Builder setCrPriceYear(int value) {
      
      crPriceYear_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *版权按年价格：0代表免费，-1代表不允许按年购买，都为-1则无法提供在线购买方式，
     * </pre>
     *
     * <code>int32 cr_price_year = 15;</code>
     */
    public Builder clearCrPriceYear() {
      
      crPriceYear_ = 0;
      onChanged();
      return this;
    }

    private int crPriceCssdownload_ ;
    /**
     * <pre>
     *CSS文件下载价格,按次收费。298元左右,-1代表不允许下载css，0代表免费
     * </pre>
     *
     * <code>int32 cr_price_cssdownload = 16;</code>
     */
    public int getCrPriceCssdownload() {
      return crPriceCssdownload_;
    }
    /**
     * <pre>
     *CSS文件下载价格,按次收费。298元左右,-1代表不允许下载css，0代表免费
     * </pre>
     *
     * <code>int32 cr_price_cssdownload = 16;</code>
     */
    public Builder setCrPriceCssdownload(int value) {
      
      crPriceCssdownload_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *CSS文件下载价格,按次收费。298元左右,-1代表不允许下载css，0代表免费
     * </pre>
     *
     * <code>int32 cr_price_cssdownload = 16;</code>
     */
    public Builder clearCrPriceCssdownload() {
      
      crPriceCssdownload_ = 0;
      onChanged();
      return this;
    }

    private boolean cdnFree_ ;
    /**
     * <pre>
     *是否免cdn流量费
     * </pre>
     *
     * <code>bool cdn_free = 17;</code>
     */
    public boolean getCdnFree() {
      return cdnFree_;
    }
    /**
     * <pre>
     *是否免cdn流量费
     * </pre>
     *
     * <code>bool cdn_free = 17;</code>
     */
    public Builder setCdnFree(boolean value) {
      
      cdnFree_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *是否免cdn流量费
     * </pre>
     *
     * <code>bool cdn_free = 17;</code>
     */
    public Builder clearCdnFree() {
      
      cdnFree_ = false;
      onChanged();
      return this;
    }

    private boolean crBuyOnMakersite_ ;
    /**
     * <pre>
     *是否可以在厂商官网购买
     * </pre>
     *
     * <code>bool cr_buy_on_makersite = 18;</code>
     */
    public boolean getCrBuyOnMakersite() {
      return crBuyOnMakersite_;
    }
    /**
     * <pre>
     *是否可以在厂商官网购买
     * </pre>
     *
     * <code>bool cr_buy_on_makersite = 18;</code>
     */
    public Builder setCrBuyOnMakersite(boolean value) {
      
      crBuyOnMakersite_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *是否可以在厂商官网购买
     * </pre>
     *
     * <code>bool cr_buy_on_makersite = 18;</code>
     */
    public Builder clearCrBuyOnMakersite() {
      
      crBuyOnMakersite_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object crUrlOnMakersite_ = "";
    /**
     * <pre>
     *当前字体在厂商的网址，如果为 "" 则自动使用厂商网址填充
     * </pre>
     *
     * <code>string cr_url_on_makersite = 19;</code>
     */
    public java.lang.String getCrUrlOnMakersite() {
      java.lang.Object ref = crUrlOnMakersite_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        crUrlOnMakersite_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *当前字体在厂商的网址，如果为 "" 则自动使用厂商网址填充
     * </pre>
     *
     * <code>string cr_url_on_makersite = 19;</code>
     */
    public com.google.protobuf.ByteString
        getCrUrlOnMakersiteBytes() {
      java.lang.Object ref = crUrlOnMakersite_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        crUrlOnMakersite_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *当前字体在厂商的网址，如果为 "" 则自动使用厂商网址填充
     * </pre>
     *
     * <code>string cr_url_on_makersite = 19;</code>
     */
    public Builder setCrUrlOnMakersite(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      crUrlOnMakersite_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *当前字体在厂商的网址，如果为 "" 则自动使用厂商网址填充
     * </pre>
     *
     * <code>string cr_url_on_makersite = 19;</code>
     */
    public Builder clearCrUrlOnMakersite() {
      
      crUrlOnMakersite_ = getDefaultInstance().getCrUrlOnMakersite();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *当前字体在厂商的网址，如果为 "" 则自动使用厂商网址填充
     * </pre>
     *
     * <code>string cr_url_on_makersite = 19;</code>
     */
    public Builder setCrUrlOnMakersiteBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      crUrlOnMakersite_ = value;
      onChanged();
      return this;
    }

    private int serviceFeeOfOnlineMonth_ ;
    /**
     * <pre>
     *通过在线购买的月服务费  0代表免费
     * </pre>
     *
     * <code>uint32 service_fee_of_online_month = 20;</code>
     */
    public int getServiceFeeOfOnlineMonth() {
      return serviceFeeOfOnlineMonth_;
    }
    /**
     * <pre>
     *通过在线购买的月服务费  0代表免费
     * </pre>
     *
     * <code>uint32 service_fee_of_online_month = 20;</code>
     */
    public Builder setServiceFeeOfOnlineMonth(int value) {
      
      serviceFeeOfOnlineMonth_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *通过在线购买的月服务费  0代表免费
     * </pre>
     *
     * <code>uint32 service_fee_of_online_month = 20;</code>
     */
    public Builder clearServiceFeeOfOnlineMonth() {
      
      serviceFeeOfOnlineMonth_ = 0;
      onChanged();
      return this;
    }

    private int serviceFeeOfOnlineYear_ ;
    /**
     * <pre>
     *通过在线购买的年服务费   0代表免费
     * </pre>
     *
     * <code>uint32 service_fee_of_online_year = 21;</code>
     */
    public int getServiceFeeOfOnlineYear() {
      return serviceFeeOfOnlineYear_;
    }
    /**
     * <pre>
     *通过在线购买的年服务费   0代表免费
     * </pre>
     *
     * <code>uint32 service_fee_of_online_year = 21;</code>
     */
    public Builder setServiceFeeOfOnlineYear(int value) {
      
      serviceFeeOfOnlineYear_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *通过在线购买的年服务费   0代表免费
     * </pre>
     *
     * <code>uint32 service_fee_of_online_year = 21;</code>
     */
    public Builder clearServiceFeeOfOnlineYear() {
      
      serviceFeeOfOnlineYear_ = 0;
      onChanged();
      return this;
    }

    private int serviceFeeOfAttorneyMonth_ ;
    /**
     * <pre>
     *通过上传授权书购买的月服务费   -1代表不允许上传授权书  0代表免费
     * </pre>
     *
     * <code>int32 service_fee_of_attorney_month = 22;</code>
     */
    public int getServiceFeeOfAttorneyMonth() {
      return serviceFeeOfAttorneyMonth_;
    }
    /**
     * <pre>
     *通过上传授权书购买的月服务费   -1代表不允许上传授权书  0代表免费
     * </pre>
     *
     * <code>int32 service_fee_of_attorney_month = 22;</code>
     */
    public Builder setServiceFeeOfAttorneyMonth(int value) {
      
      serviceFeeOfAttorneyMonth_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *通过上传授权书购买的月服务费   -1代表不允许上传授权书  0代表免费
     * </pre>
     *
     * <code>int32 service_fee_of_attorney_month = 22;</code>
     */
    public Builder clearServiceFeeOfAttorneyMonth() {
      
      serviceFeeOfAttorneyMonth_ = 0;
      onChanged();
      return this;
    }

    private int serviceFeeOfAttorneyYear_ ;
    /**
     * <pre>
     *通过上传授权书购买的年服务费    -1代表不允许上传授权书  0代表免费
     * </pre>
     *
     * <code>int32 service_fee_of_attorney_year = 23;</code>
     */
    public int getServiceFeeOfAttorneyYear() {
      return serviceFeeOfAttorneyYear_;
    }
    /**
     * <pre>
     *通过上传授权书购买的年服务费    -1代表不允许上传授权书  0代表免费
     * </pre>
     *
     * <code>int32 service_fee_of_attorney_year = 23;</code>
     */
    public Builder setServiceFeeOfAttorneyYear(int value) {
      
      serviceFeeOfAttorneyYear_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *通过上传授权书购买的年服务费    -1代表不允许上传授权书  0代表免费
     * </pre>
     *
     * <code>int32 service_fee_of_attorney_year = 23;</code>
     */
    public Builder clearServiceFeeOfAttorneyYear() {
      
      serviceFeeOfAttorneyYear_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:webfontsdk.FontMetaInfo)
  }

  // @@protoc_insertion_point(class_scope:webfontsdk.FontMetaInfo)
  private static final io.grpc.sdk.webfont.FontMetaInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.grpc.sdk.webfont.FontMetaInfo();
  }

  public static io.grpc.sdk.webfont.FontMetaInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FontMetaInfo>
      PARSER = new com.google.protobuf.AbstractParser<FontMetaInfo>() {
    @java.lang.Override
    public FontMetaInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FontMetaInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FontMetaInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FontMetaInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.grpc.sdk.webfont.FontMetaInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

