// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: webfont.proto

package io.grpc.sdk.webfont;

public interface FontMetaInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:webfontsdk.FontMetaInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *字体id
   * </pre>
   *
   * <code>uint32 font_id = 1;</code>
   */
  int getFontId();

  /**
   * <pre>
   *厂商编号
   * </pre>
   *
   * <code>uint32 maker_id = 2;</code>
   */
  int getMakerId();

  /**
   * <pre>
   *字体英文名
   * </pre>
   *
   * <code>string name_en = 3;</code>
   */
  java.lang.String getNameEn();
  /**
   * <pre>
   *字体英文名
   * </pre>
   *
   * <code>string name_en = 3;</code>
   */
  com.google.protobuf.ByteString
      getNameEnBytes();

  /**
   * <pre>
   *字体中文名
   * </pre>
   *
   * <code>string name_cn = 4;</code>
   */
  java.lang.String getNameCn();
  /**
   * <pre>
   *字体中文名
   * </pre>
   *
   * <code>string name_cn = 4;</code>
   */
  com.google.protobuf.ByteString
      getNameCnBytes();

  /**
   * <pre>
   *字体繁体名
   * </pre>
   *
   * <code>string name_tw = 5;</code>
   */
  java.lang.String getNameTw();
  /**
   * <pre>
   *字体繁体名
   * </pre>
   *
   * <code>string name_tw = 5;</code>
   */
  com.google.protobuf.ByteString
      getNameTwBytes();

  /**
   * <pre>
   *字体日文名
   * </pre>
   *
   * <code>string name_jp = 6;</code>
   */
  java.lang.String getNameJp();
  /**
   * <pre>
   *字体日文名
   * </pre>
   *
   * <code>string name_jp = 6;</code>
   */
  com.google.protobuf.ByteString
      getNameJpBytes();

  /**
   * <pre>
   *字体韩语名
   * </pre>
   *
   * <code>string name_kr = 7;</code>
   */
  java.lang.String getNameKr();
  /**
   * <pre>
   *字体韩语名
   * </pre>
   *
   * <code>string name_kr = 7;</code>
   */
  com.google.protobuf.ByteString
      getNameKrBytes();

  /**
   * <pre>
   *英语介绍
   * </pre>
   *
   * <code>string intro_en = 8;</code>
   */
  java.lang.String getIntroEn();
  /**
   * <pre>
   *英语介绍
   * </pre>
   *
   * <code>string intro_en = 8;</code>
   */
  com.google.protobuf.ByteString
      getIntroEnBytes();

  /**
   * <pre>
   *中文介绍
   * </pre>
   *
   * <code>string intro_cn = 9;</code>
   */
  java.lang.String getIntroCn();
  /**
   * <pre>
   *中文介绍
   * </pre>
   *
   * <code>string intro_cn = 9;</code>
   */
  com.google.protobuf.ByteString
      getIntroCnBytes();

  /**
   * <pre>
   *繁体中文介绍
   * </pre>
   *
   * <code>string intro_tw = 10;</code>
   */
  java.lang.String getIntroTw();
  /**
   * <pre>
   *繁体中文介绍
   * </pre>
   *
   * <code>string intro_tw = 10;</code>
   */
  com.google.protobuf.ByteString
      getIntroTwBytes();

  /**
   * <pre>
   *日语介绍
   * </pre>
   *
   * <code>string intro_jp = 11;</code>
   */
  java.lang.String getIntroJp();
  /**
   * <pre>
   *日语介绍
   * </pre>
   *
   * <code>string intro_jp = 11;</code>
   */
  com.google.protobuf.ByteString
      getIntroJpBytes();

  /**
   * <pre>
   *韩语介绍
   * </pre>
   *
   * <code>string intro_kr = 12;</code>
   */
  java.lang.String getIntroKr();
  /**
   * <pre>
   *韩语介绍
   * </pre>
   *
   * <code>string intro_kr = 12;</code>
   */
  com.google.protobuf.ByteString
      getIntroKrBytes();

  /**
   * <pre>
   *语系列表
   * </pre>
   *
   * <code>repeated .webfontsdk.Language lang = 13;</code>
   */
  java.util.List<io.grpc.sdk.webfont.Language> getLangList();
  /**
   * <pre>
   *语系列表
   * </pre>
   *
   * <code>repeated .webfontsdk.Language lang = 13;</code>
   */
  int getLangCount();
  /**
   * <pre>
   *语系列表
   * </pre>
   *
   * <code>repeated .webfontsdk.Language lang = 13;</code>
   */
  io.grpc.sdk.webfont.Language getLang(int index);
  /**
   * <pre>
   *语系列表
   * </pre>
   *
   * <code>repeated .webfontsdk.Language lang = 13;</code>
   */
  java.util.List<java.lang.Integer>
  getLangValueList();
  /**
   * <pre>
   *语系列表
   * </pre>
   *
   * <code>repeated .webfontsdk.Language lang = 13;</code>
   */
  int getLangValue(int index);

  /**
   * <pre>
   *版权授权价格：0代表免费，-1代表不允许按月购买
   * </pre>
   *
   * <code>int32 cr_price_month = 14;</code>
   */
  int getCrPriceMonth();

  /**
   * <pre>
   *版权按年价格：0代表免费，-1代表不允许按年购买，都为-1则无法提供在线购买方式，
   * </pre>
   *
   * <code>int32 cr_price_year = 15;</code>
   */
  int getCrPriceYear();

  /**
   * <pre>
   *CSS文件下载价格,按次收费。298元左右,-1代表不允许下载css，0代表免费
   * </pre>
   *
   * <code>int32 cr_price_cssdownload = 16;</code>
   */
  int getCrPriceCssdownload();

  /**
   * <pre>
   *是否免cdn流量费
   * </pre>
   *
   * <code>bool cdn_free = 17;</code>
   */
  boolean getCdnFree();

  /**
   * <pre>
   *是否可以在厂商官网购买
   * </pre>
   *
   * <code>bool cr_buy_on_makersite = 18;</code>
   */
  boolean getCrBuyOnMakersite();

  /**
   * <pre>
   *当前字体在厂商的网址，如果为 "" 则自动使用厂商网址填充
   * </pre>
   *
   * <code>string cr_url_on_makersite = 19;</code>
   */
  java.lang.String getCrUrlOnMakersite();
  /**
   * <pre>
   *当前字体在厂商的网址，如果为 "" 则自动使用厂商网址填充
   * </pre>
   *
   * <code>string cr_url_on_makersite = 19;</code>
   */
  com.google.protobuf.ByteString
      getCrUrlOnMakersiteBytes();

  /**
   * <pre>
   *通过在线购买的月服务费  0代表免费
   * </pre>
   *
   * <code>uint32 service_fee_of_online_month = 20;</code>
   */
  int getServiceFeeOfOnlineMonth();

  /**
   * <pre>
   *通过在线购买的年服务费   0代表免费
   * </pre>
   *
   * <code>uint32 service_fee_of_online_year = 21;</code>
   */
  int getServiceFeeOfOnlineYear();

  /**
   * <pre>
   *通过上传授权书购买的月服务费   -1代表不允许上传授权书  0代表免费
   * </pre>
   *
   * <code>int32 service_fee_of_attorney_month = 22;</code>
   */
  int getServiceFeeOfAttorneyMonth();

  /**
   * <pre>
   *通过上传授权书购买的年服务费    -1代表不允许上传授权书  0代表免费
   * </pre>
   *
   * <code>int32 service_fee_of_attorney_year = 23;</code>
   */
  int getServiceFeeOfAttorneyYear();
}
