// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: webfont.proto

package io.grpc.sdk.webfont;

public interface FontMakerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:webfontsdk.FontMaker)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *厂商编号
   * </pre>
   *
   * <code>uint32 maker_id = 1;</code>
   */
  int getMakerId();

  /**
   * <pre>
   *厂商网址
   * </pre>
   *
   * <code>string url = 2;</code>
   */
  java.lang.String getUrl();
  /**
   * <pre>
   *厂商网址
   * </pre>
   *
   * <code>string url = 2;</code>
   */
  com.google.protobuf.ByteString
      getUrlBytes();

  /**
   * <pre>
   *字体英文名
   * </pre>
   *
   * <code>string name_en = 3;</code>
   */
  java.lang.String getNameEn();
  /**
   * <pre>
   *字体英文名
   * </pre>
   *
   * <code>string name_en = 3;</code>
   */
  com.google.protobuf.ByteString
      getNameEnBytes();

  /**
   * <pre>
   *字体中文名
   * </pre>
   *
   * <code>string name_cn = 4;</code>
   */
  java.lang.String getNameCn();
  /**
   * <pre>
   *字体中文名
   * </pre>
   *
   * <code>string name_cn = 4;</code>
   */
  com.google.protobuf.ByteString
      getNameCnBytes();

  /**
   * <pre>
   *字体繁体名
   * </pre>
   *
   * <code>string name_tw = 5;</code>
   */
  java.lang.String getNameTw();
  /**
   * <pre>
   *字体繁体名
   * </pre>
   *
   * <code>string name_tw = 5;</code>
   */
  com.google.protobuf.ByteString
      getNameTwBytes();

  /**
   * <pre>
   *字体日文名
   * </pre>
   *
   * <code>string name_jp = 6;</code>
   */
  java.lang.String getNameJp();
  /**
   * <pre>
   *字体日文名
   * </pre>
   *
   * <code>string name_jp = 6;</code>
   */
  com.google.protobuf.ByteString
      getNameJpBytes();

  /**
   * <pre>
   *字体韩语名
   * </pre>
   *
   * <code>string name_kr = 7;</code>
   */
  java.lang.String getNameKr();
  /**
   * <pre>
   *字体韩语名
   * </pre>
   *
   * <code>string name_kr = 7;</code>
   */
  com.google.protobuf.ByteString
      getNameKrBytes();

  /**
   * <pre>
   *英语厂商介绍
   * </pre>
   *
   * <code>string intro_en = 8;</code>
   */
  java.lang.String getIntroEn();
  /**
   * <pre>
   *英语厂商介绍
   * </pre>
   *
   * <code>string intro_en = 8;</code>
   */
  com.google.protobuf.ByteString
      getIntroEnBytes();

  /**
   * <pre>
   *中文介绍
   * </pre>
   *
   * <code>string intro_cn = 9;</code>
   */
  java.lang.String getIntroCn();
  /**
   * <pre>
   *中文介绍
   * </pre>
   *
   * <code>string intro_cn = 9;</code>
   */
  com.google.protobuf.ByteString
      getIntroCnBytes();

  /**
   * <pre>
   *繁体中文介绍
   * </pre>
   *
   * <code>string intro_tw = 10;</code>
   */
  java.lang.String getIntroTw();
  /**
   * <pre>
   *繁体中文介绍
   * </pre>
   *
   * <code>string intro_tw = 10;</code>
   */
  com.google.protobuf.ByteString
      getIntroTwBytes();

  /**
   * <pre>
   *日语介绍
   * </pre>
   *
   * <code>string intro_jp = 11;</code>
   */
  java.lang.String getIntroJp();
  /**
   * <pre>
   *日语介绍
   * </pre>
   *
   * <code>string intro_jp = 11;</code>
   */
  com.google.protobuf.ByteString
      getIntroJpBytes();

  /**
   * <pre>
   *韩语介绍
   * </pre>
   *
   * <code>string intro_kr = 12;</code>
   */
  java.lang.String getIntroKr();
  /**
   * <pre>
   *韩语介绍
   * </pre>
   *
   * <code>string intro_kr = 12;</code>
   */
  com.google.protobuf.ByteString
      getIntroKrBytes();
}
