// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: webfont.proto

package io.grpc.sdk.webfont;

public interface GetAccessKeyInfoRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:webfontsdk.GetAccessKeyInfoRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string accesskey = 1;</code>
   */
  java.lang.String getAccesskey();
  /**
   * <code>string accesskey = 1;</code>
   */
  com.google.protobuf.ByteString
      getAccesskeyBytes();
}
