// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: webfont.proto

package io.grpc.sdk.webfont;

public interface GetFontMakerListRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:webfontsdk.GetFontMakerListRequest)
    com.google.protobuf.MessageOrBuilder {
}
