// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: webfont.proto

package io.grpc.sdk.webfont;

public interface GetMultGlyfsUnicodeResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:webfontsdk.GetMultGlyfsUnicodeResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;uint32, .webfontsdk.indexs&gt; unicodes = 1;</code>
   */
  int getUnicodesCount();
  /**
   * <code>map&lt;uint32, .webfontsdk.indexs&gt; unicodes = 1;</code>
   */
  boolean containsUnicodes(
      int key);
  /**
   * Use {@link #getUnicodesMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.Integer, io.grpc.sdk.webfont.indexs>
  getUnicodes();
  /**
   * <code>map&lt;uint32, .webfontsdk.indexs&gt; unicodes = 1;</code>
   */
  java.util.Map<java.lang.Integer, io.grpc.sdk.webfont.indexs>
  getUnicodesMap();
  /**
   * <code>map&lt;uint32, .webfontsdk.indexs&gt; unicodes = 1;</code>
   */

  io.grpc.sdk.webfont.indexs getUnicodesOrDefault(
      int key,
      io.grpc.sdk.webfont.indexs defaultValue);
  /**
   * <code>map&lt;uint32, .webfontsdk.indexs&gt; unicodes = 1;</code>
   */

  io.grpc.sdk.webfont.indexs getUnicodesOrThrow(
      int key);

  /**
   * <code>map&lt;uint32, bytes&gt; indexs = 3;</code>
   */
  int getIndexsCount();
  /**
   * <code>map&lt;uint32, bytes&gt; indexs = 3;</code>
   */
  boolean containsIndexs(
      int key);
  /**
   * Use {@link #getIndexsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.Integer, com.google.protobuf.ByteString>
  getIndexs();
  /**
   * <code>map&lt;uint32, bytes&gt; indexs = 3;</code>
   */
  java.util.Map<java.lang.Integer, com.google.protobuf.ByteString>
  getIndexsMap();
  /**
   * <code>map&lt;uint32, bytes&gt; indexs = 3;</code>
   */

  com.google.protobuf.ByteString getIndexsOrDefault(
      int key,
      com.google.protobuf.ByteString defaultValue);
  /**
   * <code>map&lt;uint32, bytes&gt; indexs = 3;</code>
   */

  com.google.protobuf.ByteString getIndexsOrThrow(
      int key);
}
