// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: webfont.proto

package io.grpc.sdk.webfont;

public interface GetProfileWithoutMapRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:webfontsdk.GetProfileWithoutMapRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string apikey = 1;</code>
   */
  java.lang.String getApikey();
  /**
   * <code>string apikey = 1;</code>
   */
  com.google.protobuf.ByteString
      getApikeyBytes();

  /**
   * <code>uint32 font_id = 2;</code>
   */
  int getFontId();
}
