// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: webfont.proto

package io.grpc.sdk.webfont;

public interface indexsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:webfontsdk.indexs)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated uint32 items = 2;</code>
   */
  java.util.List<java.lang.Integer> getItemsList();
  /**
   * <code>repeated uint32 items = 2;</code>
   */
  int getItemsCount();
  /**
   * <code>repeated uint32 items = 2;</code>
   */
  int getItems(int index);
}
