<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: webfont.proto

namespace Webfontsdk;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 一个完整的AccessInfo
 *
 * Generated from protobuf message <code>webfontsdk.AccessKeyInfo</code>
 */
class AccessKeyInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string accesskey = 1;</code>
     */
    private $accesskey = '';
    /**
     * Generated from protobuf field <code>uint64 user_uid = 2;</code>
     */
    private $user_uid = 0;
    /**
     * Generated from protobuf field <code>uint32 font_id = 3;</code>
     */
    private $font_id = 0;
    /**
     * Generated from protobuf field <code>int64 add_time = 4;</code>
     */
    private $add_time = 0;
    /**
     * Generated from protobuf field <code>string uuid = 5;</code>
     */
    private $uuid = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $accesskey
     *     @type int|string $user_uid
     *     @type int $font_id
     *     @type int|string $add_time
     *     @type string $uuid
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Webfont::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string accesskey = 1;</code>
     * @return string
     */
    public function getAccesskey()
    {
        return $this->accesskey;
    }

    /**
     * Generated from protobuf field <code>string accesskey = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAccesskey($var)
    {
        GPBUtil::checkString($var, True);
        $this->accesskey = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 user_uid = 2;</code>
     * @return int|string
     */
    public function getUserUid()
    {
        return $this->user_uid;
    }

    /**
     * Generated from protobuf field <code>uint64 user_uid = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserUid($var)
    {
        GPBUtil::checkUint64($var);
        $this->user_uid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 font_id = 3;</code>
     * @return int
     */
    public function getFontId()
    {
        return $this->font_id;
    }

    /**
     * Generated from protobuf field <code>uint32 font_id = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setFontId($var)
    {
        GPBUtil::checkUint32($var);
        $this->font_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 add_time = 4;</code>
     * @return int|string
     */
    public function getAddTime()
    {
        return $this->add_time;
    }

    /**
     * Generated from protobuf field <code>int64 add_time = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAddTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->add_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string uuid = 5;</code>
     * @return string
     */
    public function getUuid()
    {
        return $this->uuid;
    }

    /**
     * Generated from protobuf field <code>string uuid = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setUuid($var)
    {
        GPBUtil::checkString($var, True);
        $this->uuid = $var;

        return $this;
    }

}

