<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: webfont.proto

namespace Webfontsdk;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>webfontsdk.FontBuildRequest</code>
 */
class FontBuildRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string apikey = 1;</code>
     */
    private $apikey = '';
    /**
     * Generated from protobuf field <code>uint32 font_id = 2;</code>
     */
    private $font_id = 0;
    /**
     * Generated from protobuf field <code>string text = 3;</code>
     */
    private $text = '';
    /**
     * Generated from protobuf field <code>bool need_ttf = 4;</code>
     */
    private $need_ttf = false;
    /**
     * Generated from protobuf field <code>bool need_eot = 5;</code>
     */
    private $need_eot = false;
    /**
     * Generated from protobuf field <code>bool need_woff = 6;</code>
     */
    private $need_woff = false;
    /**
     * Generated from protobuf field <code>bool need_woff2 = 7;</code>
     */
    private $need_woff2 = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $apikey
     *     @type int $font_id
     *     @type string $text
     *     @type bool $need_ttf
     *     @type bool $need_eot
     *     @type bool $need_woff
     *     @type bool $need_woff2
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Webfont::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string apikey = 1;</code>
     * @return string
     */
    public function getApikey()
    {
        return $this->apikey;
    }

    /**
     * Generated from protobuf field <code>string apikey = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setApikey($var)
    {
        GPBUtil::checkString($var, True);
        $this->apikey = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 font_id = 2;</code>
     * @return int
     */
    public function getFontId()
    {
        return $this->font_id;
    }

    /**
     * Generated from protobuf field <code>uint32 font_id = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setFontId($var)
    {
        GPBUtil::checkUint32($var);
        $this->font_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string text = 3;</code>
     * @return string
     */
    public function getText()
    {
        return $this->text;
    }

    /**
     * Generated from protobuf field <code>string text = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setText($var)
    {
        GPBUtil::checkString($var, True);
        $this->text = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool need_ttf = 4;</code>
     * @return bool
     */
    public function getNeedTtf()
    {
        return $this->need_ttf;
    }

    /**
     * Generated from protobuf field <code>bool need_ttf = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setNeedTtf($var)
    {
        GPBUtil::checkBool($var);
        $this->need_ttf = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool need_eot = 5;</code>
     * @return bool
     */
    public function getNeedEot()
    {
        return $this->need_eot;
    }

    /**
     * Generated from protobuf field <code>bool need_eot = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setNeedEot($var)
    {
        GPBUtil::checkBool($var);
        $this->need_eot = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool need_woff = 6;</code>
     * @return bool
     */
    public function getNeedWoff()
    {
        return $this->need_woff;
    }

    /**
     * Generated from protobuf field <code>bool need_woff = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setNeedWoff($var)
    {
        GPBUtil::checkBool($var);
        $this->need_woff = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool need_woff2 = 7;</code>
     * @return bool
     */
    public function getNeedWoff2()
    {
        return $this->need_woff2;
    }

    /**
     * Generated from protobuf field <code>bool need_woff2 = 7;</code>
     * @param bool $var
     * @return $this
     */
    public function setNeedWoff2($var)
    {
        GPBUtil::checkBool($var);
        $this->need_woff2 = $var;

        return $this;
    }

}

