<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: webfont.proto

namespace Webfontsdk;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>webfontsdk.GetFontListReply</code>
 */
class GetFontListReply extends \Google\Protobuf\Internal\Message
{
    /**
     *字体列表
     *
     * Generated from protobuf field <code>repeated .webfontsdk.FontMetaInfo items = 2;</code>
     */
    private $items;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \gRPC\FontMetaInfo[]|\Google\Protobuf\Internal\RepeatedField $items
     *          字体列表
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Webfont::initOnce();
        parent::__construct($data);
    }

    /**
     *字体列表
     *
     * Generated from protobuf field <code>repeated .webfontsdk.FontMetaInfo items = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getItems()
    {
        return $this->items;
    }

    /**
     *字体列表
     *
     * Generated from protobuf field <code>repeated .webfontsdk.FontMetaInfo items = 2;</code>
     * @param \gRPC\FontMetaInfo[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setItems($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \gRPC\FontMetaInfo::class);
        $this->items = $arr;

        return $this;
    }

}

