<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: webfont.proto

namespace Webfontsdk;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>webfontsdk.GetMultGlyfsUnicodeResult</code>
 */
class GetMultGlyfsUnicodeResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>map<uint32, .webfontsdk.indexs> unicodes = 1;</code>
     */
    private $unicodes;
    /**
     * Generated from protobuf field <code>map<uint32, bytes> indexs = 3;</code>
     */
    private $indexs;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array|\Google\Protobuf\Internal\MapField $unicodes
     *     @type array|\Google\Protobuf\Internal\MapField $indexs
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Webfont::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>map<uint32, .webfontsdk.indexs> unicodes = 1;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getUnicodes()
    {
        return $this->unicodes;
    }

    /**
     * Generated from protobuf field <code>map<uint32, .webfontsdk.indexs> unicodes = 1;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setUnicodes($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::UINT32, \Google\Protobuf\Internal\GPBType::MESSAGE, \gRPC\indexs::class);
        $this->unicodes = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<uint32, bytes> indexs = 3;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getIndexs()
    {
        return $this->indexs;
    }

    /**
     * Generated from protobuf field <code>map<uint32, bytes> indexs = 3;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setIndexs($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::UINT32, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->indexs = $arr;

        return $this;
    }

}

