<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: webfont.proto

namespace Webfontsdk;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *GetProfile for html5
 *
 * Generated from protobuf message <code>webfontsdk.GetProfileWithoutMapRequest</code>
 */
class GetProfileWithoutMapRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string apikey = 1;</code>
     */
    private $apikey = '';
    /**
     * Generated from protobuf field <code>uint32 font_id = 2;</code>
     */
    private $font_id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $apikey
     *     @type int $font_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Webfont::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string apikey = 1;</code>
     * @return string
     */
    public function getApikey()
    {
        return $this->apikey;
    }

    /**
     * Generated from protobuf field <code>string apikey = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setApikey($var)
    {
        GPBUtil::checkString($var, True);
        $this->apikey = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 font_id = 2;</code>
     * @return int
     */
    public function getFontId()
    {
        return $this->font_id;
    }

    /**
     * Generated from protobuf field <code>uint32 font_id = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setFontId($var)
    {
        GPBUtil::checkUint32($var);
        $this->font_id = $var;

        return $this;
    }

}

