<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: webfont.proto

namespace Webfontsdk;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>webfontsdk.GetUseRateResult</code>
 */
class GetUseRateResult extends \Google\Protobuf\Internal\Message
{
    /**
     *repeated UseRate items=1;
     *
     * Generated from protobuf field <code>map<uint32, uint32> items = 1;</code>
     */
    private $items;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array|\Google\Protobuf\Internal\MapField $items
     *          repeated UseRate items=1;
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Webfont::initOnce();
        parent::__construct($data);
    }

    /**
     *repeated UseRate items=1;
     *
     * Generated from protobuf field <code>map<uint32, uint32> items = 1;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getItems()
    {
        return $this->items;
    }

    /**
     *repeated UseRate items=1;
     *
     * Generated from protobuf field <code>map<uint32, uint32> items = 1;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setItems($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::UINT32, \Google\Protobuf\Internal\GPBType::UINT32);
        $this->items = $arr;

        return $this;
    }

}

