<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: webfont.proto

namespace Webfontsdk;

use UnexpectedValueException;

/**
 * Protobuf type <code>webfontsdk.Language</code>
 */
class Language
{
    /**
     * Generated from protobuf enum <code>UNKNOW = 0;</code>
     */
    const UNKNOW = 0;
    /**
     * Generated from protobuf enum <code>English = 1;</code>
     */
    const English = 1;
    /**
     * Generated from protobuf enum <code>Simplified_Chinese = 2;</code>
     */
    const Simplified_Chinese = 2;
    /**
     * Generated from protobuf enum <code>Traditional_Chinese = 3;</code>
     */
    const Traditional_Chinese = 3;
    /**
     * Generated from protobuf enum <code>Japanese = 4;</code>
     */
    const Japanese = 4;
    /**
     * Generated from protobuf enum <code>Korean = 5;</code>
     */
    const Korean = 5;

    private static $valueToName = [
        self::UNKNOW => 'UNKNOW',
        self::English => 'English',
        self::Simplified_Chinese => 'Simplified_Chinese',
        self::Traditional_Chinese => 'Traditional_Chinese',
        self::Japanese => 'Japanese',
        self::Korean => 'Korean',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

