<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: webfont.proto

namespace Webfontsdk;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *AddAccessKeyRequest 新增一个accesskey(增)
 *
 * Generated from protobuf message <code>webfontsdk.MakesureAccessKeyRequest</code>
 */
class MakesureAccessKeyRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 user_uid = 1;</code>
     */
    private $user_uid = 0;
    /**
     * Generated from protobuf field <code>uint32 font_id = 2;</code>
     */
    private $font_id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $user_uid
     *     @type int $font_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Webfont::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 user_uid = 1;</code>
     * @return int|string
     */
    public function getUserUid()
    {
        return $this->user_uid;
    }

    /**
     * Generated from protobuf field <code>uint64 user_uid = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setUserUid($var)
    {
        GPBUtil::checkUint64($var);
        $this->user_uid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 font_id = 2;</code>
     * @return int
     */
    public function getFontId()
    {
        return $this->font_id;
    }

    /**
     * Generated from protobuf field <code>uint32 font_id = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setFontId($var)
    {
        GPBUtil::checkUint32($var);
        $this->font_id = $var;

        return $this;
    }

}

